// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: service.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ExampleService_Ping_FullMethodName = "/service.v1.ExampleService/Ping"
)

// ExampleServiceClient is the client API for ExampleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ExampleService is a placeholder — rename and extend per domain.
type ExampleServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type exampleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewExampleServiceClient(cc grpc.ClientConnInterface) ExampleServiceClient {
	return &exampleServiceClient{cc}
}

func (c *exampleServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, ExampleService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ExampleServiceServer is the server API for ExampleService service.
// All implementations must embed UnimplementedExampleServiceServer
// for forward compatibility.
//
// ExampleService is a placeholder — rename and extend per domain.
type ExampleServiceServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedExampleServiceServer()
}

// UnimplementedExampleServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedExampleServiceServer struct{}

func (UnimplementedExampleServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedExampleServiceServer) mustEmbedUnimplementedExampleServiceServer() {}
func (UnimplementedExampleServiceServer) testEmbeddedByValue()                        {}

// UnsafeExampleServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ExampleServiceServer will
// result in compilation errors.
type UnsafeExampleServiceServer interface {
	mustEmbedUnimplementedExampleServiceServer()
}

func RegisterExampleServiceServer(s grpc.ServiceRegistrar, srv ExampleServiceServer) {
	// If the following call panics, it indicates UnimplementedExampleServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ExampleService_ServiceDesc, srv)
}

func _ExampleService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ExampleServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ExampleService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ExampleServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ExampleService_ServiceDesc is the grpc.ServiceDesc for ExampleService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ExampleService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.v1.ExampleService",
	HandlerType: (*ExampleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _ExampleService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

const (
	DocumentWorkflowService_CreateDraft_FullMethodName                = "/service.v1.DocumentWorkflowService/CreateDraft"
	DocumentWorkflowService_UpdateDraft_FullMethodName                = "/service.v1.DocumentWorkflowService/UpdateDraft"
	DocumentWorkflowService_GetDocument_FullMethodName                = "/service.v1.DocumentWorkflowService/GetDocument"
	DocumentWorkflowService_GetEditorControlProfile_FullMethodName    = "/service.v1.DocumentWorkflowService/GetEditorControlProfile"
	DocumentWorkflowService_UpdateEditorControlProfile_FullMethodName = "/service.v1.DocumentWorkflowService/UpdateEditorControlProfile"
	DocumentWorkflowService_CreateExportRequest_FullMethodName        = "/service.v1.DocumentWorkflowService/CreateExportRequest"
	DocumentWorkflowService_GetExportRequest_FullMethodName           = "/service.v1.DocumentWorkflowService/GetExportRequest"
	DocumentWorkflowService_DownloadExportArtifact_FullMethodName     = "/service.v1.DocumentWorkflowService/DownloadExportArtifact"
	DocumentWorkflowService_SearchDocuments_FullMethodName            = "/service.v1.DocumentWorkflowService/SearchDocuments"
	DocumentWorkflowService_SubmitWorkflow_FullMethodName             = "/service.v1.DocumentWorkflowService/SubmitWorkflow"
	DocumentWorkflowService_ApproveWorkflow_FullMethodName            = "/service.v1.DocumentWorkflowService/ApproveWorkflow"
	DocumentWorkflowService_RequestWorkflowChanges_FullMethodName     = "/service.v1.DocumentWorkflowService/RequestWorkflowChanges"
	DocumentWorkflowService_ArchiveDocument_FullMethodName            = "/service.v1.DocumentWorkflowService/ArchiveDocument"
)

// DocumentWorkflowServiceClient is the client API for DocumentWorkflowService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocumentWorkflowServiceClient interface {
	CreateDraft(ctx context.Context, in *CreateDraftRequest, opts ...grpc.CallOption) (*Document, error)
	UpdateDraft(ctx context.Context, in *UpdateDraftRequest, opts ...grpc.CallOption) (*Document, error)
	GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*Document, error)
	GetEditorControlProfile(ctx context.Context, in *GetEditorControlProfileRequest, opts ...grpc.CallOption) (*EditorControlProfile, error)
	UpdateEditorControlProfile(ctx context.Context, in *UpdateEditorControlProfileRequest, opts ...grpc.CallOption) (*EditorControlProfile, error)
	CreateExportRequest(ctx context.Context, in *CreateExportPayload, opts ...grpc.CallOption) (*ExportRequest, error)
	GetExportRequest(ctx context.Context, in *GetExportRequestRequest, opts ...grpc.CallOption) (*ExportRequest, error)
	DownloadExportArtifact(ctx context.Context, in *DownloadExportArtifactRequest, opts ...grpc.CallOption) (*DownloadExportArtifactResponse, error)
	SearchDocuments(ctx context.Context, in *SearchDocumentsRequest, opts ...grpc.CallOption) (*SearchDocumentsResponse, error)
	SubmitWorkflow(ctx context.Context, in *SubmitWorkflowRequest, opts ...grpc.CallOption) (*WorkflowInstance, error)
	ApproveWorkflow(ctx context.Context, in *ApproveWorkflowRequest, opts ...grpc.CallOption) (*WorkflowInstance, error)
	RequestWorkflowChanges(ctx context.Context, in *RequestWorkflowChangesRequest, opts ...grpc.CallOption) (*WorkflowInstance, error)
	ArchiveDocument(ctx context.Context, in *ArchiveDocumentRequest, opts ...grpc.CallOption) (*ArchiveDocumentResponse, error)
}

type documentWorkflowServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentWorkflowServiceClient(cc grpc.ClientConnInterface) DocumentWorkflowServiceClient {
	return &documentWorkflowServiceClient{cc}
}

func (c *documentWorkflowServiceClient) CreateDraft(ctx context.Context, in *CreateDraftRequest, opts ...grpc.CallOption) (*Document, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Document)
	err := c.cc.Invoke(ctx, DocumentWorkflowService_CreateDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentWorkflowServiceClient) UpdateDraft(ctx context.Context, in *UpdateDraftRequest, opts ...grpc.CallOption) (*Document, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Document)
	err := c.cc.Invoke(ctx, DocumentWorkflowService_UpdateDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentWorkflowServiceClient) GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*Document, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Document)
	err := c.cc.Invoke(ctx, DocumentWorkflowService_GetDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentWorkflowServiceClient) GetEditorControlProfile(ctx context.Context, in *GetEditorControlProfileRequest, opts ...grpc.CallOption) (*EditorControlProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EditorControlProfile)
	err := c.cc.Invoke(ctx, DocumentWorkflowService_GetEditorControlProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentWorkflowServiceClient) UpdateEditorControlProfile(ctx context.Context, in *UpdateEditorControlProfileRequest, opts ...grpc.CallOption) (*EditorControlProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EditorControlProfile)
	err := c.cc.Invoke(ctx, DocumentWorkflowService_UpdateEditorControlProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentWorkflowServiceClient) CreateExportRequest(ctx context.Context, in *CreateExportPayload, opts ...grpc.CallOption) (*ExportRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportRequest)
	err := c.cc.Invoke(ctx, DocumentWorkflowService_CreateExportRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentWorkflowServiceClient) GetExportRequest(ctx context.Context, in *GetExportRequestRequest, opts ...grpc.CallOption) (*ExportRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportRequest)
	err := c.cc.Invoke(ctx, DocumentWorkflowService_GetExportRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentWorkflowServiceClient) DownloadExportArtifact(ctx context.Context, in *DownloadExportArtifactRequest, opts ...grpc.CallOption) (*DownloadExportArtifactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadExportArtifactResponse)
	err := c.cc.Invoke(ctx, DocumentWorkflowService_DownloadExportArtifact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentWorkflowServiceClient) SearchDocuments(ctx context.Context, in *SearchDocumentsRequest, opts ...grpc.CallOption) (*SearchDocumentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchDocumentsResponse)
	err := c.cc.Invoke(ctx, DocumentWorkflowService_SearchDocuments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentWorkflowServiceClient) SubmitWorkflow(ctx context.Context, in *SubmitWorkflowRequest, opts ...grpc.CallOption) (*WorkflowInstance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowInstance)
	err := c.cc.Invoke(ctx, DocumentWorkflowService_SubmitWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentWorkflowServiceClient) ApproveWorkflow(ctx context.Context, in *ApproveWorkflowRequest, opts ...grpc.CallOption) (*WorkflowInstance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowInstance)
	err := c.cc.Invoke(ctx, DocumentWorkflowService_ApproveWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentWorkflowServiceClient) RequestWorkflowChanges(ctx context.Context, in *RequestWorkflowChangesRequest, opts ...grpc.CallOption) (*WorkflowInstance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowInstance)
	err := c.cc.Invoke(ctx, DocumentWorkflowService_RequestWorkflowChanges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentWorkflowServiceClient) ArchiveDocument(ctx context.Context, in *ArchiveDocumentRequest, opts ...grpc.CallOption) (*ArchiveDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArchiveDocumentResponse)
	err := c.cc.Invoke(ctx, DocumentWorkflowService_ArchiveDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentWorkflowServiceServer is the server API for DocumentWorkflowService service.
// All implementations must embed UnimplementedDocumentWorkflowServiceServer
// for forward compatibility.
type DocumentWorkflowServiceServer interface {
	CreateDraft(context.Context, *CreateDraftRequest) (*Document, error)
	UpdateDraft(context.Context, *UpdateDraftRequest) (*Document, error)
	GetDocument(context.Context, *GetDocumentRequest) (*Document, error)
	GetEditorControlProfile(context.Context, *GetEditorControlProfileRequest) (*EditorControlProfile, error)
	UpdateEditorControlProfile(context.Context, *UpdateEditorControlProfileRequest) (*EditorControlProfile, error)
	CreateExportRequest(context.Context, *CreateExportPayload) (*ExportRequest, error)
	GetExportRequest(context.Context, *GetExportRequestRequest) (*ExportRequest, error)
	DownloadExportArtifact(context.Context, *DownloadExportArtifactRequest) (*DownloadExportArtifactResponse, error)
	SearchDocuments(context.Context, *SearchDocumentsRequest) (*SearchDocumentsResponse, error)
	SubmitWorkflow(context.Context, *SubmitWorkflowRequest) (*WorkflowInstance, error)
	ApproveWorkflow(context.Context, *ApproveWorkflowRequest) (*WorkflowInstance, error)
	RequestWorkflowChanges(context.Context, *RequestWorkflowChangesRequest) (*WorkflowInstance, error)
	ArchiveDocument(context.Context, *ArchiveDocumentRequest) (*ArchiveDocumentResponse, error)
	mustEmbedUnimplementedDocumentWorkflowServiceServer()
}

// UnimplementedDocumentWorkflowServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocumentWorkflowServiceServer struct{}

func (UnimplementedDocumentWorkflowServiceServer) CreateDraft(context.Context, *CreateDraftRequest) (*Document, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDraft not implemented")
}
func (UnimplementedDocumentWorkflowServiceServer) UpdateDraft(context.Context, *UpdateDraftRequest) (*Document, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDraft not implemented")
}
func (UnimplementedDocumentWorkflowServiceServer) GetDocument(context.Context, *GetDocumentRequest) (*Document, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDocument not implemented")
}
func (UnimplementedDocumentWorkflowServiceServer) GetEditorControlProfile(context.Context, *GetEditorControlProfileRequest) (*EditorControlProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEditorControlProfile not implemented")
}
func (UnimplementedDocumentWorkflowServiceServer) UpdateEditorControlProfile(context.Context, *UpdateEditorControlProfileRequest) (*EditorControlProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEditorControlProfile not implemented")
}
func (UnimplementedDocumentWorkflowServiceServer) CreateExportRequest(context.Context, *CreateExportPayload) (*ExportRequest, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateExportRequest not implemented")
}
func (UnimplementedDocumentWorkflowServiceServer) GetExportRequest(context.Context, *GetExportRequestRequest) (*ExportRequest, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExportRequest not implemented")
}
func (UnimplementedDocumentWorkflowServiceServer) DownloadExportArtifact(context.Context, *DownloadExportArtifactRequest) (*DownloadExportArtifactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DownloadExportArtifact not implemented")
}
func (UnimplementedDocumentWorkflowServiceServer) SearchDocuments(context.Context, *SearchDocumentsRequest) (*SearchDocumentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchDocuments not implemented")
}
func (UnimplementedDocumentWorkflowServiceServer) SubmitWorkflow(context.Context, *SubmitWorkflowRequest) (*WorkflowInstance, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitWorkflow not implemented")
}
func (UnimplementedDocumentWorkflowServiceServer) ApproveWorkflow(context.Context, *ApproveWorkflowRequest) (*WorkflowInstance, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveWorkflow not implemented")
}
func (UnimplementedDocumentWorkflowServiceServer) RequestWorkflowChanges(context.Context, *RequestWorkflowChangesRequest) (*WorkflowInstance, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestWorkflowChanges not implemented")
}
func (UnimplementedDocumentWorkflowServiceServer) ArchiveDocument(context.Context, *ArchiveDocumentRequest) (*ArchiveDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ArchiveDocument not implemented")
}
func (UnimplementedDocumentWorkflowServiceServer) mustEmbedUnimplementedDocumentWorkflowServiceServer() {
}
func (UnimplementedDocumentWorkflowServiceServer) testEmbeddedByValue() {}

// UnsafeDocumentWorkflowServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentWorkflowServiceServer will
// result in compilation errors.
type UnsafeDocumentWorkflowServiceServer interface {
	mustEmbedUnimplementedDocumentWorkflowServiceServer()
}

func RegisterDocumentWorkflowServiceServer(s grpc.ServiceRegistrar, srv DocumentWorkflowServiceServer) {
	// If the following call panics, it indicates UnimplementedDocumentWorkflowServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DocumentWorkflowService_ServiceDesc, srv)
}

func _DocumentWorkflowService_CreateDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentWorkflowServiceServer).CreateDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentWorkflowService_CreateDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentWorkflowServiceServer).CreateDraft(ctx, req.(*CreateDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentWorkflowService_UpdateDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentWorkflowServiceServer).UpdateDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentWorkflowService_UpdateDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentWorkflowServiceServer).UpdateDraft(ctx, req.(*UpdateDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentWorkflowService_GetDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentWorkflowServiceServer).GetDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentWorkflowService_GetDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentWorkflowServiceServer).GetDocument(ctx, req.(*GetDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentWorkflowService_GetEditorControlProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEditorControlProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentWorkflowServiceServer).GetEditorControlProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentWorkflowService_GetEditorControlProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentWorkflowServiceServer).GetEditorControlProfile(ctx, req.(*GetEditorControlProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentWorkflowService_UpdateEditorControlProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEditorControlProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentWorkflowServiceServer).UpdateEditorControlProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentWorkflowService_UpdateEditorControlProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentWorkflowServiceServer).UpdateEditorControlProfile(ctx, req.(*UpdateEditorControlProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentWorkflowService_CreateExportRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExportPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentWorkflowServiceServer).CreateExportRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentWorkflowService_CreateExportRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentWorkflowServiceServer).CreateExportRequest(ctx, req.(*CreateExportPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentWorkflowService_GetExportRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExportRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentWorkflowServiceServer).GetExportRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentWorkflowService_GetExportRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentWorkflowServiceServer).GetExportRequest(ctx, req.(*GetExportRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentWorkflowService_DownloadExportArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadExportArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentWorkflowServiceServer).DownloadExportArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentWorkflowService_DownloadExportArtifact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentWorkflowServiceServer).DownloadExportArtifact(ctx, req.(*DownloadExportArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentWorkflowService_SearchDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentWorkflowServiceServer).SearchDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentWorkflowService_SearchDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentWorkflowServiceServer).SearchDocuments(ctx, req.(*SearchDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentWorkflowService_SubmitWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentWorkflowServiceServer).SubmitWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentWorkflowService_SubmitWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentWorkflowServiceServer).SubmitWorkflow(ctx, req.(*SubmitWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentWorkflowService_ApproveWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentWorkflowServiceServer).ApproveWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentWorkflowService_ApproveWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentWorkflowServiceServer).ApproveWorkflow(ctx, req.(*ApproveWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentWorkflowService_RequestWorkflowChanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestWorkflowChangesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentWorkflowServiceServer).RequestWorkflowChanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentWorkflowService_RequestWorkflowChanges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentWorkflowServiceServer).RequestWorkflowChanges(ctx, req.(*RequestWorkflowChangesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentWorkflowService_ArchiveDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentWorkflowServiceServer).ArchiveDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentWorkflowService_ArchiveDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentWorkflowServiceServer).ArchiveDocument(ctx, req.(*ArchiveDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DocumentWorkflowService_ServiceDesc is the grpc.ServiceDesc for DocumentWorkflowService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocumentWorkflowService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.v1.DocumentWorkflowService",
	HandlerType: (*DocumentWorkflowServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDraft",
			Handler:    _DocumentWorkflowService_CreateDraft_Handler,
		},
		{
			MethodName: "UpdateDraft",
			Handler:    _DocumentWorkflowService_UpdateDraft_Handler,
		},
		{
			MethodName: "GetDocument",
			Handler:    _DocumentWorkflowService_GetDocument_Handler,
		},
		{
			MethodName: "GetEditorControlProfile",
			Handler:    _DocumentWorkflowService_GetEditorControlProfile_Handler,
		},
		{
			MethodName: "UpdateEditorControlProfile",
			Handler:    _DocumentWorkflowService_UpdateEditorControlProfile_Handler,
		},
		{
			MethodName: "CreateExportRequest",
			Handler:    _DocumentWorkflowService_CreateExportRequest_Handler,
		},
		{
			MethodName: "GetExportRequest",
			Handler:    _DocumentWorkflowService_GetExportRequest_Handler,
		},
		{
			MethodName: "DownloadExportArtifact",
			Handler:    _DocumentWorkflowService_DownloadExportArtifact_Handler,
		},
		{
			MethodName: "SearchDocuments",
			Handler:    _DocumentWorkflowService_SearchDocuments_Handler,
		},
		{
			MethodName: "SubmitWorkflow",
			Handler:    _DocumentWorkflowService_SubmitWorkflow_Handler,
		},
		{
			MethodName: "ApproveWorkflow",
			Handler:    _DocumentWorkflowService_ApproveWorkflow_Handler,
		},
		{
			MethodName: "RequestWorkflowChanges",
			Handler:    _DocumentWorkflowService_RequestWorkflowChanges_Handler,
		},
		{
			MethodName: "ArchiveDocument",
			Handler:    _DocumentWorkflowService_ArchiveDocument_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

const (
	SearchNotificationService_SyncSearchProjection_FullMethodName     = "/service.v1.SearchNotificationService/SyncSearchProjection"
	SearchNotificationService_SearchDocuments_FullMethodName          = "/service.v1.SearchNotificationService/SearchDocuments"
	SearchNotificationService_EmitNotification_FullMethodName         = "/service.v1.SearchNotificationService/EmitNotification"
	SearchNotificationService_RetryFailedNotifications_FullMethodName = "/service.v1.SearchNotificationService/RetryFailedNotifications"
)

// SearchNotificationServiceClient is the client API for SearchNotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SearchNotificationServiceClient interface {
	SyncSearchProjection(ctx context.Context, in *SyncSearchProjectionRequest, opts ...grpc.CallOption) (*SyncSearchProjectionResponse, error)
	SearchDocuments(ctx context.Context, in *SearchDocumentsRequest, opts ...grpc.CallOption) (*SearchDocumentsResponse, error)
	EmitNotification(ctx context.Context, in *EmitNotificationRequest, opts ...grpc.CallOption) (*EmitNotificationResponse, error)
	RetryFailedNotifications(ctx context.Context, in *RetryFailedNotificationsRequest, opts ...grpc.CallOption) (*RetryFailedNotificationsResponse, error)
}

type searchNotificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchNotificationServiceClient(cc grpc.ClientConnInterface) SearchNotificationServiceClient {
	return &searchNotificationServiceClient{cc}
}

func (c *searchNotificationServiceClient) SyncSearchProjection(ctx context.Context, in *SyncSearchProjectionRequest, opts ...grpc.CallOption) (*SyncSearchProjectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncSearchProjectionResponse)
	err := c.cc.Invoke(ctx, SearchNotificationService_SyncSearchProjection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchNotificationServiceClient) SearchDocuments(ctx context.Context, in *SearchDocumentsRequest, opts ...grpc.CallOption) (*SearchDocumentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchDocumentsResponse)
	err := c.cc.Invoke(ctx, SearchNotificationService_SearchDocuments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchNotificationServiceClient) EmitNotification(ctx context.Context, in *EmitNotificationRequest, opts ...grpc.CallOption) (*EmitNotificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmitNotificationResponse)
	err := c.cc.Invoke(ctx, SearchNotificationService_EmitNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchNotificationServiceClient) RetryFailedNotifications(ctx context.Context, in *RetryFailedNotificationsRequest, opts ...grpc.CallOption) (*RetryFailedNotificationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetryFailedNotificationsResponse)
	err := c.cc.Invoke(ctx, SearchNotificationService_RetryFailedNotifications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchNotificationServiceServer is the server API for SearchNotificationService service.
// All implementations must embed UnimplementedSearchNotificationServiceServer
// for forward compatibility.
type SearchNotificationServiceServer interface {
	SyncSearchProjection(context.Context, *SyncSearchProjectionRequest) (*SyncSearchProjectionResponse, error)
	SearchDocuments(context.Context, *SearchDocumentsRequest) (*SearchDocumentsResponse, error)
	EmitNotification(context.Context, *EmitNotificationRequest) (*EmitNotificationResponse, error)
	RetryFailedNotifications(context.Context, *RetryFailedNotificationsRequest) (*RetryFailedNotificationsResponse, error)
	mustEmbedUnimplementedSearchNotificationServiceServer()
}

// UnimplementedSearchNotificationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSearchNotificationServiceServer struct{}

func (UnimplementedSearchNotificationServiceServer) SyncSearchProjection(context.Context, *SyncSearchProjectionRequest) (*SyncSearchProjectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SyncSearchProjection not implemented")
}
func (UnimplementedSearchNotificationServiceServer) SearchDocuments(context.Context, *SearchDocumentsRequest) (*SearchDocumentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchDocuments not implemented")
}
func (UnimplementedSearchNotificationServiceServer) EmitNotification(context.Context, *EmitNotificationRequest) (*EmitNotificationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EmitNotification not implemented")
}
func (UnimplementedSearchNotificationServiceServer) RetryFailedNotifications(context.Context, *RetryFailedNotificationsRequest) (*RetryFailedNotificationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetryFailedNotifications not implemented")
}
func (UnimplementedSearchNotificationServiceServer) mustEmbedUnimplementedSearchNotificationServiceServer() {
}
func (UnimplementedSearchNotificationServiceServer) testEmbeddedByValue() {}

// UnsafeSearchNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchNotificationServiceServer will
// result in compilation errors.
type UnsafeSearchNotificationServiceServer interface {
	mustEmbedUnimplementedSearchNotificationServiceServer()
}

func RegisterSearchNotificationServiceServer(s grpc.ServiceRegistrar, srv SearchNotificationServiceServer) {
	// If the following call panics, it indicates UnimplementedSearchNotificationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SearchNotificationService_ServiceDesc, srv)
}

func _SearchNotificationService_SyncSearchProjection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncSearchProjectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchNotificationServiceServer).SyncSearchProjection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchNotificationService_SyncSearchProjection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchNotificationServiceServer).SyncSearchProjection(ctx, req.(*SyncSearchProjectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchNotificationService_SearchDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchNotificationServiceServer).SearchDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchNotificationService_SearchDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchNotificationServiceServer).SearchDocuments(ctx, req.(*SearchDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchNotificationService_EmitNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmitNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchNotificationServiceServer).EmitNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchNotificationService_EmitNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchNotificationServiceServer).EmitNotification(ctx, req.(*EmitNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchNotificationService_RetryFailedNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryFailedNotificationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchNotificationServiceServer).RetryFailedNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SearchNotificationService_RetryFailedNotifications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchNotificationServiceServer).RetryFailedNotifications(ctx, req.(*RetryFailedNotificationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SearchNotificationService_ServiceDesc is the grpc.ServiceDesc for SearchNotificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SearchNotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.v1.SearchNotificationService",
	HandlerType: (*SearchNotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SyncSearchProjection",
			Handler:    _SearchNotificationService_SyncSearchProjection_Handler,
		},
		{
			MethodName: "SearchDocuments",
			Handler:    _SearchNotificationService_SearchDocuments_Handler,
		},
		{
			MethodName: "EmitNotification",
			Handler:    _SearchNotificationService_EmitNotification_Handler,
		},
		{
			MethodName: "RetryFailedNotifications",
			Handler:    _SearchNotificationService_RetryFailedNotifications_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

const (
	DocumentService_CreateDraft_FullMethodName                = "/service.v1.DocumentService/CreateDraft"
	DocumentService_UpdateDraft_FullMethodName                = "/service.v1.DocumentService/UpdateDraft"
	DocumentService_GetDocument_FullMethodName                = "/service.v1.DocumentService/GetDocument"
	DocumentService_GetEditorControlProfile_FullMethodName    = "/service.v1.DocumentService/GetEditorControlProfile"
	DocumentService_UpdateEditorControlProfile_FullMethodName = "/service.v1.DocumentService/UpdateEditorControlProfile"
	DocumentService_CreateExportRequest_FullMethodName        = "/service.v1.DocumentService/CreateExportRequest"
	DocumentService_GetExportRequest_FullMethodName           = "/service.v1.DocumentService/GetExportRequest"
	DocumentService_DownloadExportArtifact_FullMethodName     = "/service.v1.DocumentService/DownloadExportArtifact"
	DocumentService_SearchDocuments_FullMethodName            = "/service.v1.DocumentService/SearchDocuments"
	DocumentService_ArchiveDocument_FullMethodName            = "/service.v1.DocumentService/ArchiveDocument"
)

// DocumentServiceClient is the client API for DocumentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DocumentServiceClient interface {
	CreateDraft(ctx context.Context, in *CreateDraftRequest, opts ...grpc.CallOption) (*Document, error)
	UpdateDraft(ctx context.Context, in *UpdateDraftRequest, opts ...grpc.CallOption) (*Document, error)
	GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*Document, error)
	GetEditorControlProfile(ctx context.Context, in *GetEditorControlProfileRequest, opts ...grpc.CallOption) (*EditorControlProfile, error)
	UpdateEditorControlProfile(ctx context.Context, in *UpdateEditorControlProfileRequest, opts ...grpc.CallOption) (*EditorControlProfile, error)
	CreateExportRequest(ctx context.Context, in *CreateExportPayload, opts ...grpc.CallOption) (*ExportRequest, error)
	GetExportRequest(ctx context.Context, in *GetExportRequestRequest, opts ...grpc.CallOption) (*ExportRequest, error)
	DownloadExportArtifact(ctx context.Context, in *DownloadExportArtifactRequest, opts ...grpc.CallOption) (*DownloadExportArtifactResponse, error)
	SearchDocuments(ctx context.Context, in *SearchDocumentsRequest, opts ...grpc.CallOption) (*SearchDocumentsResponse, error)
	ArchiveDocument(ctx context.Context, in *ArchiveDocumentRequest, opts ...grpc.CallOption) (*ArchiveDocumentResponse, error)
}

type documentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentServiceClient(cc grpc.ClientConnInterface) DocumentServiceClient {
	return &documentServiceClient{cc}
}

func (c *documentServiceClient) CreateDraft(ctx context.Context, in *CreateDraftRequest, opts ...grpc.CallOption) (*Document, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Document)
	err := c.cc.Invoke(ctx, DocumentService_CreateDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) UpdateDraft(ctx context.Context, in *UpdateDraftRequest, opts ...grpc.CallOption) (*Document, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Document)
	err := c.cc.Invoke(ctx, DocumentService_UpdateDraft_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) GetDocument(ctx context.Context, in *GetDocumentRequest, opts ...grpc.CallOption) (*Document, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Document)
	err := c.cc.Invoke(ctx, DocumentService_GetDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) GetEditorControlProfile(ctx context.Context, in *GetEditorControlProfileRequest, opts ...grpc.CallOption) (*EditorControlProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EditorControlProfile)
	err := c.cc.Invoke(ctx, DocumentService_GetEditorControlProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) UpdateEditorControlProfile(ctx context.Context, in *UpdateEditorControlProfileRequest, opts ...grpc.CallOption) (*EditorControlProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EditorControlProfile)
	err := c.cc.Invoke(ctx, DocumentService_UpdateEditorControlProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) CreateExportRequest(ctx context.Context, in *CreateExportPayload, opts ...grpc.CallOption) (*ExportRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportRequest)
	err := c.cc.Invoke(ctx, DocumentService_CreateExportRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) GetExportRequest(ctx context.Context, in *GetExportRequestRequest, opts ...grpc.CallOption) (*ExportRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportRequest)
	err := c.cc.Invoke(ctx, DocumentService_GetExportRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) DownloadExportArtifact(ctx context.Context, in *DownloadExportArtifactRequest, opts ...grpc.CallOption) (*DownloadExportArtifactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DownloadExportArtifactResponse)
	err := c.cc.Invoke(ctx, DocumentService_DownloadExportArtifact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) SearchDocuments(ctx context.Context, in *SearchDocumentsRequest, opts ...grpc.CallOption) (*SearchDocumentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchDocumentsResponse)
	err := c.cc.Invoke(ctx, DocumentService_SearchDocuments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) ArchiveDocument(ctx context.Context, in *ArchiveDocumentRequest, opts ...grpc.CallOption) (*ArchiveDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ArchiveDocumentResponse)
	err := c.cc.Invoke(ctx, DocumentService_ArchiveDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentServiceServer is the server API for DocumentService service.
// All implementations must embed UnimplementedDocumentServiceServer
// for forward compatibility.
type DocumentServiceServer interface {
	CreateDraft(context.Context, *CreateDraftRequest) (*Document, error)
	UpdateDraft(context.Context, *UpdateDraftRequest) (*Document, error)
	GetDocument(context.Context, *GetDocumentRequest) (*Document, error)
	GetEditorControlProfile(context.Context, *GetEditorControlProfileRequest) (*EditorControlProfile, error)
	UpdateEditorControlProfile(context.Context, *UpdateEditorControlProfileRequest) (*EditorControlProfile, error)
	CreateExportRequest(context.Context, *CreateExportPayload) (*ExportRequest, error)
	GetExportRequest(context.Context, *GetExportRequestRequest) (*ExportRequest, error)
	DownloadExportArtifact(context.Context, *DownloadExportArtifactRequest) (*DownloadExportArtifactResponse, error)
	SearchDocuments(context.Context, *SearchDocumentsRequest) (*SearchDocumentsResponse, error)
	ArchiveDocument(context.Context, *ArchiveDocumentRequest) (*ArchiveDocumentResponse, error)
	mustEmbedUnimplementedDocumentServiceServer()
}

// UnimplementedDocumentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDocumentServiceServer struct{}

func (UnimplementedDocumentServiceServer) CreateDraft(context.Context, *CreateDraftRequest) (*Document, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDraft not implemented")
}
func (UnimplementedDocumentServiceServer) UpdateDraft(context.Context, *UpdateDraftRequest) (*Document, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateDraft not implemented")
}
func (UnimplementedDocumentServiceServer) GetDocument(context.Context, *GetDocumentRequest) (*Document, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDocument not implemented")
}
func (UnimplementedDocumentServiceServer) GetEditorControlProfile(context.Context, *GetEditorControlProfileRequest) (*EditorControlProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEditorControlProfile not implemented")
}
func (UnimplementedDocumentServiceServer) UpdateEditorControlProfile(context.Context, *UpdateEditorControlProfileRequest) (*EditorControlProfile, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEditorControlProfile not implemented")
}
func (UnimplementedDocumentServiceServer) CreateExportRequest(context.Context, *CreateExportPayload) (*ExportRequest, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateExportRequest not implemented")
}
func (UnimplementedDocumentServiceServer) GetExportRequest(context.Context, *GetExportRequestRequest) (*ExportRequest, error) {
	return nil, status.Error(codes.Unimplemented, "method GetExportRequest not implemented")
}
func (UnimplementedDocumentServiceServer) DownloadExportArtifact(context.Context, *DownloadExportArtifactRequest) (*DownloadExportArtifactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DownloadExportArtifact not implemented")
}
func (UnimplementedDocumentServiceServer) SearchDocuments(context.Context, *SearchDocumentsRequest) (*SearchDocumentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchDocuments not implemented")
}
func (UnimplementedDocumentServiceServer) ArchiveDocument(context.Context, *ArchiveDocumentRequest) (*ArchiveDocumentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ArchiveDocument not implemented")
}
func (UnimplementedDocumentServiceServer) mustEmbedUnimplementedDocumentServiceServer() {}
func (UnimplementedDocumentServiceServer) testEmbeddedByValue()                         {}

// UnsafeDocumentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DocumentServiceServer will
// result in compilation errors.
type UnsafeDocumentServiceServer interface {
	mustEmbedUnimplementedDocumentServiceServer()
}

func RegisterDocumentServiceServer(s grpc.ServiceRegistrar, srv DocumentServiceServer) {
	// If the following call panics, it indicates UnimplementedDocumentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DocumentService_ServiceDesc, srv)
}

func _DocumentService_CreateDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).CreateDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_CreateDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).CreateDraft(ctx, req.(*CreateDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_UpdateDraft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDraftRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).UpdateDraft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_UpdateDraft_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).UpdateDraft(ctx, req.(*UpdateDraftRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_GetDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).GetDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_GetDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).GetDocument(ctx, req.(*GetDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_GetEditorControlProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEditorControlProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).GetEditorControlProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_GetEditorControlProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).GetEditorControlProfile(ctx, req.(*GetEditorControlProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_UpdateEditorControlProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEditorControlProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).UpdateEditorControlProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_UpdateEditorControlProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).UpdateEditorControlProfile(ctx, req.(*UpdateEditorControlProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_CreateExportRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExportPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).CreateExportRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_CreateExportRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).CreateExportRequest(ctx, req.(*CreateExportPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_GetExportRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetExportRequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).GetExportRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_GetExportRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).GetExportRequest(ctx, req.(*GetExportRequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_DownloadExportArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadExportArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).DownloadExportArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_DownloadExportArtifact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).DownloadExportArtifact(ctx, req.(*DownloadExportArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_SearchDocuments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchDocumentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).SearchDocuments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_SearchDocuments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).SearchDocuments(ctx, req.(*SearchDocumentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_ArchiveDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ArchiveDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).ArchiveDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DocumentService_ArchiveDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).ArchiveDocument(ctx, req.(*ArchiveDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DocumentService_ServiceDesc is the grpc.ServiceDesc for DocumentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DocumentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.v1.DocumentService",
	HandlerType: (*DocumentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDraft",
			Handler:    _DocumentService_CreateDraft_Handler,
		},
		{
			MethodName: "UpdateDraft",
			Handler:    _DocumentService_UpdateDraft_Handler,
		},
		{
			MethodName: "GetDocument",
			Handler:    _DocumentService_GetDocument_Handler,
		},
		{
			MethodName: "GetEditorControlProfile",
			Handler:    _DocumentService_GetEditorControlProfile_Handler,
		},
		{
			MethodName: "UpdateEditorControlProfile",
			Handler:    _DocumentService_UpdateEditorControlProfile_Handler,
		},
		{
			MethodName: "CreateExportRequest",
			Handler:    _DocumentService_CreateExportRequest_Handler,
		},
		{
			MethodName: "GetExportRequest",
			Handler:    _DocumentService_GetExportRequest_Handler,
		},
		{
			MethodName: "DownloadExportArtifact",
			Handler:    _DocumentService_DownloadExportArtifact_Handler,
		},
		{
			MethodName: "SearchDocuments",
			Handler:    _DocumentService_SearchDocuments_Handler,
		},
		{
			MethodName: "ArchiveDocument",
			Handler:    _DocumentService_ArchiveDocument_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

const (
	WorkflowService_StartWorkflow_FullMethodName  = "/service.v1.WorkflowService/StartWorkflow"
	WorkflowService_ApproveStep_FullMethodName    = "/service.v1.WorkflowService/ApproveStep"
	WorkflowService_RejectStep_FullMethodName     = "/service.v1.WorkflowService/RejectStep"
	WorkflowService_RequestChanges_FullMethodName = "/service.v1.WorkflowService/RequestChanges"
)

// WorkflowServiceClient is the client API for WorkflowService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WorkflowServiceClient interface {
	StartWorkflow(ctx context.Context, in *StartWorkflowRequest, opts ...grpc.CallOption) (*WorkflowInstance, error)
	ApproveStep(ctx context.Context, in *ApproveStepRequest, opts ...grpc.CallOption) (*WorkflowInstance, error)
	RejectStep(ctx context.Context, in *RejectStepRequest, opts ...grpc.CallOption) (*WorkflowInstance, error)
	RequestChanges(ctx context.Context, in *RequestChangesRequest, opts ...grpc.CallOption) (*WorkflowInstance, error)
}

type workflowServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkflowServiceClient(cc grpc.ClientConnInterface) WorkflowServiceClient {
	return &workflowServiceClient{cc}
}

func (c *workflowServiceClient) StartWorkflow(ctx context.Context, in *StartWorkflowRequest, opts ...grpc.CallOption) (*WorkflowInstance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowInstance)
	err := c.cc.Invoke(ctx, WorkflowService_StartWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) ApproveStep(ctx context.Context, in *ApproveStepRequest, opts ...grpc.CallOption) (*WorkflowInstance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowInstance)
	err := c.cc.Invoke(ctx, WorkflowService_ApproveStep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) RejectStep(ctx context.Context, in *RejectStepRequest, opts ...grpc.CallOption) (*WorkflowInstance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowInstance)
	err := c.cc.Invoke(ctx, WorkflowService_RejectStep_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) RequestChanges(ctx context.Context, in *RequestChangesRequest, opts ...grpc.CallOption) (*WorkflowInstance, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowInstance)
	err := c.cc.Invoke(ctx, WorkflowService_RequestChanges_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkflowServiceServer is the server API for WorkflowService service.
// All implementations must embed UnimplementedWorkflowServiceServer
// for forward compatibility.
type WorkflowServiceServer interface {
	StartWorkflow(context.Context, *StartWorkflowRequest) (*WorkflowInstance, error)
	ApproveStep(context.Context, *ApproveStepRequest) (*WorkflowInstance, error)
	RejectStep(context.Context, *RejectStepRequest) (*WorkflowInstance, error)
	RequestChanges(context.Context, *RequestChangesRequest) (*WorkflowInstance, error)
	mustEmbedUnimplementedWorkflowServiceServer()
}

// UnimplementedWorkflowServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkflowServiceServer struct{}

func (UnimplementedWorkflowServiceServer) StartWorkflow(context.Context, *StartWorkflowRequest) (*WorkflowInstance, error) {
	return nil, status.Error(codes.Unimplemented, "method StartWorkflow not implemented")
}
func (UnimplementedWorkflowServiceServer) ApproveStep(context.Context, *ApproveStepRequest) (*WorkflowInstance, error) {
	return nil, status.Error(codes.Unimplemented, "method ApproveStep not implemented")
}
func (UnimplementedWorkflowServiceServer) RejectStep(context.Context, *RejectStepRequest) (*WorkflowInstance, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectStep not implemented")
}
func (UnimplementedWorkflowServiceServer) RequestChanges(context.Context, *RequestChangesRequest) (*WorkflowInstance, error) {
	return nil, status.Error(codes.Unimplemented, "method RequestChanges not implemented")
}
func (UnimplementedWorkflowServiceServer) mustEmbedUnimplementedWorkflowServiceServer() {}
func (UnimplementedWorkflowServiceServer) testEmbeddedByValue()                         {}

// UnsafeWorkflowServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkflowServiceServer will
// result in compilation errors.
type UnsafeWorkflowServiceServer interface {
	mustEmbedUnimplementedWorkflowServiceServer()
}

func RegisterWorkflowServiceServer(s grpc.ServiceRegistrar, srv WorkflowServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkflowServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkflowService_ServiceDesc, srv)
}

func _WorkflowService_StartWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).StartWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_StartWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).StartWorkflow(ctx, req.(*StartWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_ApproveStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApproveStepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).ApproveStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_ApproveStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).ApproveStep(ctx, req.(*ApproveStepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_RejectStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectStepRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).RejectStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_RejectStep_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).RejectStep(ctx, req.(*RejectStepRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_RequestChanges_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestChangesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).RequestChanges(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_RequestChanges_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).RequestChanges(ctx, req.(*RequestChangesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkflowService_ServiceDesc is the grpc.ServiceDesc for WorkflowService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkflowService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.v1.WorkflowService",
	HandlerType: (*WorkflowServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartWorkflow",
			Handler:    _WorkflowService_StartWorkflow_Handler,
		},
		{
			MethodName: "ApproveStep",
			Handler:    _WorkflowService_ApproveStep_Handler,
		},
		{
			MethodName: "RejectStep",
			Handler:    _WorkflowService_RejectStep_Handler,
		},
		{
			MethodName: "RequestChanges",
			Handler:    _WorkflowService_RequestChanges_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

const (
	SignatureService_StartSignature_FullMethodName          = "/service.v1.SignatureService/StartSignature"
	SignatureService_RecordSignatureCallback_FullMethodName = "/service.v1.SignatureService/RecordSignatureCallback"
	SignatureService_GetSignatureStatus_FullMethodName      = "/service.v1.SignatureService/GetSignatureStatus"
)

// SignatureServiceClient is the client API for SignatureService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SignatureServiceClient interface {
	StartSignature(ctx context.Context, in *StartSignatureRequest, opts ...grpc.CallOption) (*SignatureRequest, error)
	RecordSignatureCallback(ctx context.Context, in *RecordSignatureCallbackRequest, opts ...grpc.CallOption) (*SignatureRequest, error)
	GetSignatureStatus(ctx context.Context, in *GetSignatureStatusRequest, opts ...grpc.CallOption) (*SignatureRequest, error)
}

type signatureServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSignatureServiceClient(cc grpc.ClientConnInterface) SignatureServiceClient {
	return &signatureServiceClient{cc}
}

func (c *signatureServiceClient) StartSignature(ctx context.Context, in *StartSignatureRequest, opts ...grpc.CallOption) (*SignatureRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignatureRequest)
	err := c.cc.Invoke(ctx, SignatureService_StartSignature_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signatureServiceClient) RecordSignatureCallback(ctx context.Context, in *RecordSignatureCallbackRequest, opts ...grpc.CallOption) (*SignatureRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignatureRequest)
	err := c.cc.Invoke(ctx, SignatureService_RecordSignatureCallback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signatureServiceClient) GetSignatureStatus(ctx context.Context, in *GetSignatureStatusRequest, opts ...grpc.CallOption) (*SignatureRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignatureRequest)
	err := c.cc.Invoke(ctx, SignatureService_GetSignatureStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SignatureServiceServer is the server API for SignatureService service.
// All implementations must embed UnimplementedSignatureServiceServer
// for forward compatibility.
type SignatureServiceServer interface {
	StartSignature(context.Context, *StartSignatureRequest) (*SignatureRequest, error)
	RecordSignatureCallback(context.Context, *RecordSignatureCallbackRequest) (*SignatureRequest, error)
	GetSignatureStatus(context.Context, *GetSignatureStatusRequest) (*SignatureRequest, error)
	mustEmbedUnimplementedSignatureServiceServer()
}

// UnimplementedSignatureServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSignatureServiceServer struct{}

func (UnimplementedSignatureServiceServer) StartSignature(context.Context, *StartSignatureRequest) (*SignatureRequest, error) {
	return nil, status.Error(codes.Unimplemented, "method StartSignature not implemented")
}
func (UnimplementedSignatureServiceServer) RecordSignatureCallback(context.Context, *RecordSignatureCallbackRequest) (*SignatureRequest, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordSignatureCallback not implemented")
}
func (UnimplementedSignatureServiceServer) GetSignatureStatus(context.Context, *GetSignatureStatusRequest) (*SignatureRequest, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSignatureStatus not implemented")
}
func (UnimplementedSignatureServiceServer) mustEmbedUnimplementedSignatureServiceServer() {}
func (UnimplementedSignatureServiceServer) testEmbeddedByValue()                          {}

// UnsafeSignatureServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SignatureServiceServer will
// result in compilation errors.
type UnsafeSignatureServiceServer interface {
	mustEmbedUnimplementedSignatureServiceServer()
}

func RegisterSignatureServiceServer(s grpc.ServiceRegistrar, srv SignatureServiceServer) {
	// If the following call panics, it indicates UnimplementedSignatureServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SignatureService_ServiceDesc, srv)
}

func _SignatureService_StartSignature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSignatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignatureServiceServer).StartSignature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SignatureService_StartSignature_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignatureServiceServer).StartSignature(ctx, req.(*StartSignatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SignatureService_RecordSignatureCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordSignatureCallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignatureServiceServer).RecordSignatureCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SignatureService_RecordSignatureCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignatureServiceServer).RecordSignatureCallback(ctx, req.(*RecordSignatureCallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SignatureService_GetSignatureStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSignatureStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignatureServiceServer).GetSignatureStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SignatureService_GetSignatureStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignatureServiceServer).GetSignatureStatus(ctx, req.(*GetSignatureStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SignatureService_ServiceDesc is the grpc.ServiceDesc for SignatureService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SignatureService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.v1.SignatureService",
	HandlerType: (*SignatureServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartSignature",
			Handler:    _SignatureService_StartSignature_Handler,
		},
		{
			MethodName: "RecordSignatureCallback",
			Handler:    _SignatureService_RecordSignatureCallback_Handler,
		},
		{
			MethodName: "GetSignatureStatus",
			Handler:    _SignatureService_GetSignatureStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

const (
	NotificationService_EmitNotification_FullMethodName         = "/service.v1.NotificationService/EmitNotification"
	NotificationService_RetryFailedNotifications_FullMethodName = "/service.v1.NotificationService/RetryFailedNotifications"
)

// NotificationServiceClient is the client API for NotificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotificationServiceClient interface {
	EmitNotification(ctx context.Context, in *EmitNotificationRequest, opts ...grpc.CallOption) (*EmitNotificationResponse, error)
	RetryFailedNotifications(ctx context.Context, in *RetryFailedNotificationsRequest, opts ...grpc.CallOption) (*RetryFailedNotificationsResponse, error)
}

type notificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotificationServiceClient(cc grpc.ClientConnInterface) NotificationServiceClient {
	return &notificationServiceClient{cc}
}

func (c *notificationServiceClient) EmitNotification(ctx context.Context, in *EmitNotificationRequest, opts ...grpc.CallOption) (*EmitNotificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmitNotificationResponse)
	err := c.cc.Invoke(ctx, NotificationService_EmitNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notificationServiceClient) RetryFailedNotifications(ctx context.Context, in *RetryFailedNotificationsRequest, opts ...grpc.CallOption) (*RetryFailedNotificationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RetryFailedNotificationsResponse)
	err := c.cc.Invoke(ctx, NotificationService_RetryFailedNotifications_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotificationServiceServer is the server API for NotificationService service.
// All implementations must embed UnimplementedNotificationServiceServer
// for forward compatibility.
type NotificationServiceServer interface {
	EmitNotification(context.Context, *EmitNotificationRequest) (*EmitNotificationResponse, error)
	RetryFailedNotifications(context.Context, *RetryFailedNotificationsRequest) (*RetryFailedNotificationsResponse, error)
	mustEmbedUnimplementedNotificationServiceServer()
}

// UnimplementedNotificationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotificationServiceServer struct{}

func (UnimplementedNotificationServiceServer) EmitNotification(context.Context, *EmitNotificationRequest) (*EmitNotificationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EmitNotification not implemented")
}
func (UnimplementedNotificationServiceServer) RetryFailedNotifications(context.Context, *RetryFailedNotificationsRequest) (*RetryFailedNotificationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RetryFailedNotifications not implemented")
}
func (UnimplementedNotificationServiceServer) mustEmbedUnimplementedNotificationServiceServer() {}
func (UnimplementedNotificationServiceServer) testEmbeddedByValue()                             {}

// UnsafeNotificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotificationServiceServer will
// result in compilation errors.
type UnsafeNotificationServiceServer interface {
	mustEmbedUnimplementedNotificationServiceServer()
}

func RegisterNotificationServiceServer(s grpc.ServiceRegistrar, srv NotificationServiceServer) {
	// If the following call panics, it indicates UnimplementedNotificationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NotificationService_ServiceDesc, srv)
}

func _NotificationService_EmitNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmitNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).EmitNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_EmitNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).EmitNotification(ctx, req.(*EmitNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotificationService_RetryFailedNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetryFailedNotificationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationServiceServer).RetryFailedNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotificationService_RetryFailedNotifications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationServiceServer).RetryFailedNotifications(ctx, req.(*RetryFailedNotificationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotificationService_ServiceDesc is the grpc.ServiceDesc for NotificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.v1.NotificationService",
	HandlerType: (*NotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EmitNotification",
			Handler:    _NotificationService_EmitNotification_Handler,
		},
		{
			MethodName: "RetryFailedNotifications",
			Handler:    _NotificationService_RetryFailedNotifications_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
