// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: service.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Document struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title               string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Category            string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Status              string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	OwnerUserId         string                 `protobuf:"bytes,5,opt,name=owner_user_id,json=ownerUserId,proto3" json:"owner_user_id,omitempty"`
	Version             int64                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	UpdatedAt           string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ContentDocumentJson string                 `protobuf:"bytes,8,opt,name=content_document_json,json=contentDocumentJson,proto3" json:"content_document_json,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Document) Reset() {
	*x = Document{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Document) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Document) ProtoMessage() {}

func (x *Document) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Document.ProtoReflect.Descriptor instead.
func (*Document) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *Document) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Document) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Document) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Document) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Document) GetOwnerUserId() string {
	if x != nil {
		return x.OwnerUserId
	}
	return ""
}

func (x *Document) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Document) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Document) GetContentDocumentJson() string {
	if x != nil {
		return x.ContentDocumentJson
	}
	return ""
}

type EditorControlProfile struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ContextType      string                 `protobuf:"bytes,2,opt,name=context_type,json=contextType,proto3" json:"context_type,omitempty"`
	ContextKey       string                 `protobuf:"bytes,3,opt,name=context_key,json=contextKey,proto3" json:"context_key,omitempty"`
	EnabledControls  []string               `protobuf:"bytes,4,rep,name=enabled_controls,json=enabledControls,proto3" json:"enabled_controls,omitempty"`
	DisabledControls []string               `protobuf:"bytes,5,rep,name=disabled_controls,json=disabledControls,proto3" json:"disabled_controls,omitempty"`
	IsActive         bool                   `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	UpdatedByUserId  string                 `protobuf:"bytes,7,opt,name=updated_by_user_id,json=updatedByUserId,proto3" json:"updated_by_user_id,omitempty"`
	UpdatedAt        string                 `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EditorControlProfile) Reset() {
	*x = EditorControlProfile{}
	mi := &file_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditorControlProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditorControlProfile) ProtoMessage() {}

func (x *EditorControlProfile) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditorControlProfile.ProtoReflect.Descriptor instead.
func (*EditorControlProfile) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *EditorControlProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EditorControlProfile) GetContextType() string {
	if x != nil {
		return x.ContextType
	}
	return ""
}

func (x *EditorControlProfile) GetContextKey() string {
	if x != nil {
		return x.ContextKey
	}
	return ""
}

func (x *EditorControlProfile) GetEnabledControls() []string {
	if x != nil {
		return x.EnabledControls
	}
	return nil
}

func (x *EditorControlProfile) GetDisabledControls() []string {
	if x != nil {
		return x.DisabledControls
	}
	return nil
}

func (x *EditorControlProfile) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *EditorControlProfile) GetUpdatedByUserId() string {
	if x != nil {
		return x.UpdatedByUserId
	}
	return ""
}

func (x *EditorControlProfile) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type ExportArtifact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportArtifact) Reset() {
	*x = ExportArtifact{}
	mi := &file_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportArtifact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportArtifact) ProtoMessage() {}

func (x *ExportArtifact) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportArtifact.ProtoReflect.Descriptor instead.
func (*ExportArtifact) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *ExportArtifact) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExportArtifact) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *ExportArtifact) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *ExportArtifact) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ExportArtifact) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type ExportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	SourceVersion int64                  `protobuf:"varint,4,opt,name=source_version,json=sourceVersion,proto3" json:"source_version,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,6,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Artifact      *ExportArtifact        `protobuf:"bytes,8,opt,name=artifact,proto3" json:"artifact,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportRequest) Reset() {
	*x = ExportRequest{}
	mi := &file_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRequest) ProtoMessage() {}

func (x *ExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRequest.ProtoReflect.Descriptor instead.
func (*ExportRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *ExportRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExportRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *ExportRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ExportRequest) GetSourceVersion() int64 {
	if x != nil {
		return x.SourceVersion
	}
	return 0
}

func (x *ExportRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExportRequest) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ExportRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ExportRequest) GetArtifact() *ExportArtifact {
	if x != nil {
		return x.Artifact
	}
	return nil
}

func (x *ExportRequest) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *ExportRequest) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type WorkflowInstance struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DocumentId      string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	CurrentStepCode string                 `protobuf:"bytes,3,opt,name=current_step_code,json=currentStepCode,proto3" json:"current_step_code,omitempty"`
	Status          string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	AssignedUserId  string                 `protobuf:"bytes,5,opt,name=assigned_user_id,json=assignedUserId,proto3" json:"assigned_user_id,omitempty"`
	UpdatedAt       string                 `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WorkflowInstance) Reset() {
	*x = WorkflowInstance{}
	mi := &file_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowInstance) ProtoMessage() {}

func (x *WorkflowInstance) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowInstance.ProtoReflect.Descriptor instead.
func (*WorkflowInstance) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *WorkflowInstance) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkflowInstance) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *WorkflowInstance) GetCurrentStepCode() string {
	if x != nil {
		return x.CurrentStepCode
	}
	return ""
}

func (x *WorkflowInstance) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkflowInstance) GetAssignedUserId() string {
	if x != nil {
		return x.AssignedUserId
	}
	return ""
}

func (x *WorkflowInstance) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type SignatureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ProviderRef   string                 `protobuf:"bytes,4,opt,name=provider_ref,json=providerRef,proto3" json:"provider_ref,omitempty"`
	DueAt         string                 `protobuf:"bytes,5,opt,name=due_at,json=dueAt,proto3" json:"due_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignatureRequest) Reset() {
	*x = SignatureRequest{}
	mi := &file_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignatureRequest) ProtoMessage() {}

func (x *SignatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignatureRequest.ProtoReflect.Descriptor instead.
func (*SignatureRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7}
}

func (x *SignatureRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SignatureRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *SignatureRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SignatureRequest) GetProviderRef() string {
	if x != nil {
		return x.ProviderRef
	}
	return ""
}

func (x *SignatureRequest) GetDueAt() string {
	if x != nil {
		return x.DueAt
	}
	return ""
}

type CreateDraftRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ActorUserId         string                 `protobuf:"bytes,1,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	Title               string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Category            string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	ContentDocumentJson string                 `protobuf:"bytes,4,opt,name=content_document_json,json=contentDocumentJson,proto3" json:"content_document_json,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateDraftRequest) Reset() {
	*x = CreateDraftRequest{}
	mi := &file_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDraftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDraftRequest) ProtoMessage() {}

func (x *CreateDraftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDraftRequest.ProtoReflect.Descriptor instead.
func (*CreateDraftRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{8}
}

func (x *CreateDraftRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *CreateDraftRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateDraftRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateDraftRequest) GetContentDocumentJson() string {
	if x != nil {
		return x.ContentDocumentJson
	}
	return ""
}

type UpdateDraftRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ActorUserId         string                 `protobuf:"bytes,1,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	DocumentId          string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Title               string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	ExpectedVersion     int64                  `protobuf:"varint,4,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	ContentDocumentJson string                 `protobuf:"bytes,5,opt,name=content_document_json,json=contentDocumentJson,proto3" json:"content_document_json,omitempty"`
	Status              string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdateDraftRequest) Reset() {
	*x = UpdateDraftRequest{}
	mi := &file_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDraftRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDraftRequest) ProtoMessage() {}

func (x *UpdateDraftRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDraftRequest.ProtoReflect.Descriptor instead.
func (*UpdateDraftRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateDraftRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *UpdateDraftRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *UpdateDraftRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateDraftRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

func (x *UpdateDraftRequest) GetContentDocumentJson() string {
	if x != nil {
		return x.ContentDocumentJson
	}
	return ""
}

func (x *UpdateDraftRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetDocumentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorUserId   string                 `protobuf:"bytes,1,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDocumentRequest) Reset() {
	*x = GetDocumentRequest{}
	mi := &file_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDocumentRequest) ProtoMessage() {}

func (x *GetDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDocumentRequest.ProtoReflect.Descriptor instead.
func (*GetDocumentRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{10}
}

func (x *GetDocumentRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *GetDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type GetEditorControlProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorUserId   string                 `protobuf:"bytes,1,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	ContextType   string                 `protobuf:"bytes,2,opt,name=context_type,json=contextType,proto3" json:"context_type,omitempty"`
	ContextKey    string                 `protobuf:"bytes,3,opt,name=context_key,json=contextKey,proto3" json:"context_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEditorControlProfileRequest) Reset() {
	*x = GetEditorControlProfileRequest{}
	mi := &file_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEditorControlProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEditorControlProfileRequest) ProtoMessage() {}

func (x *GetEditorControlProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEditorControlProfileRequest.ProtoReflect.Descriptor instead.
func (*GetEditorControlProfileRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetEditorControlProfileRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *GetEditorControlProfileRequest) GetContextType() string {
	if x != nil {
		return x.ContextType
	}
	return ""
}

func (x *GetEditorControlProfileRequest) GetContextKey() string {
	if x != nil {
		return x.ContextKey
	}
	return ""
}

type UpdateEditorControlProfileRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ActorUserId      string                 `protobuf:"bytes,1,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	ProfileId        string                 `protobuf:"bytes,2,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	EnabledControls  []string               `protobuf:"bytes,3,rep,name=enabled_controls,json=enabledControls,proto3" json:"enabled_controls,omitempty"`
	DisabledControls []string               `protobuf:"bytes,4,rep,name=disabled_controls,json=disabledControls,proto3" json:"disabled_controls,omitempty"`
	IsActive         bool                   `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateEditorControlProfileRequest) Reset() {
	*x = UpdateEditorControlProfileRequest{}
	mi := &file_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEditorControlProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEditorControlProfileRequest) ProtoMessage() {}

func (x *UpdateEditorControlProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEditorControlProfileRequest.ProtoReflect.Descriptor instead.
func (*UpdateEditorControlProfileRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateEditorControlProfileRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *UpdateEditorControlProfileRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *UpdateEditorControlProfileRequest) GetEnabledControls() []string {
	if x != nil {
		return x.EnabledControls
	}
	return nil
}

func (x *UpdateEditorControlProfileRequest) GetDisabledControls() []string {
	if x != nil {
		return x.DisabledControls
	}
	return nil
}

func (x *UpdateEditorControlProfileRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type CreateExportPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorUserId   string                 `protobuf:"bytes,1,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	SourceVersion int64                  `protobuf:"varint,4,opt,name=source_version,json=sourceVersion,proto3" json:"source_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateExportPayload) Reset() {
	*x = CreateExportPayload{}
	mi := &file_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateExportPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateExportPayload) ProtoMessage() {}

func (x *CreateExportPayload) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateExportPayload.ProtoReflect.Descriptor instead.
func (*CreateExportPayload) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{13}
}

func (x *CreateExportPayload) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *CreateExportPayload) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *CreateExportPayload) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *CreateExportPayload) GetSourceVersion() int64 {
	if x != nil {
		return x.SourceVersion
	}
	return 0
}

type GetExportRequestRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ActorUserId     string                 `protobuf:"bytes,1,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	DocumentId      string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	ExportRequestId string                 `protobuf:"bytes,3,opt,name=export_request_id,json=exportRequestId,proto3" json:"export_request_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetExportRequestRequest) Reset() {
	*x = GetExportRequestRequest{}
	mi := &file_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExportRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExportRequestRequest) ProtoMessage() {}

func (x *GetExportRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExportRequestRequest.ProtoReflect.Descriptor instead.
func (*GetExportRequestRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{14}
}

func (x *GetExportRequestRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *GetExportRequestRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *GetExportRequestRequest) GetExportRequestId() string {
	if x != nil {
		return x.ExportRequestId
	}
	return ""
}

type DownloadExportArtifactRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ActorUserId     string                 `protobuf:"bytes,1,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	DocumentId      string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	ExportRequestId string                 `protobuf:"bytes,3,opt,name=export_request_id,json=exportRequestId,proto3" json:"export_request_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DownloadExportArtifactRequest) Reset() {
	*x = DownloadExportArtifactRequest{}
	mi := &file_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadExportArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadExportArtifactRequest) ProtoMessage() {}

func (x *DownloadExportArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadExportArtifactRequest.ProtoReflect.Descriptor instead.
func (*DownloadExportArtifactRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{15}
}

func (x *DownloadExportArtifactRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *DownloadExportArtifactRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *DownloadExportArtifactRequest) GetExportRequestId() string {
	if x != nil {
		return x.ExportRequestId
	}
	return ""
}

type DownloadExportArtifactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	FileName      string                 `protobuf:"bytes,2,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	MimeType      string                 `protobuf:"bytes,3,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadExportArtifactResponse) Reset() {
	*x = DownloadExportArtifactResponse{}
	mi := &file_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadExportArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadExportArtifactResponse) ProtoMessage() {}

func (x *DownloadExportArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadExportArtifactResponse.ProtoReflect.Descriptor instead.
func (*DownloadExportArtifactResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{16}
}

func (x *DownloadExportArtifactResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DownloadExportArtifactResponse) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *DownloadExportArtifactResponse) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type SearchDocumentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorUserId   string                 `protobuf:"bytes,1,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,6,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchDocumentsRequest) Reset() {
	*x = SearchDocumentsRequest{}
	mi := &file_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchDocumentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchDocumentsRequest) ProtoMessage() {}

func (x *SearchDocumentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchDocumentsRequest.ProtoReflect.Descriptor instead.
func (*SearchDocumentsRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{17}
}

func (x *SearchDocumentsRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *SearchDocumentsRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchDocumentsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SearchDocumentsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *SearchDocumentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SearchDocumentsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type SearchDocumentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Document            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchDocumentsResponse) Reset() {
	*x = SearchDocumentsResponse{}
	mi := &file_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchDocumentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchDocumentsResponse) ProtoMessage() {}

func (x *SearchDocumentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchDocumentsResponse.ProtoReflect.Descriptor instead.
func (*SearchDocumentsResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{18}
}

func (x *SearchDocumentsResponse) GetItems() []*Document {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *SearchDocumentsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ArchiveDocumentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ActorUserId     string                 `protobuf:"bytes,1,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	DocumentId      string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	ExpectedVersion int64                  `protobuf:"varint,3,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ArchiveDocumentRequest) Reset() {
	*x = ArchiveDocumentRequest{}
	mi := &file_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveDocumentRequest) ProtoMessage() {}

func (x *ArchiveDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveDocumentRequest.ProtoReflect.Descriptor instead.
func (*ArchiveDocumentRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{19}
}

func (x *ArchiveDocumentRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *ArchiveDocumentRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *ArchiveDocumentRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type ArchiveDocumentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Archived      bool                   `protobuf:"varint,1,opt,name=archived,proto3" json:"archived,omitempty"`
	ArchivedAt    string                 `protobuf:"bytes,2,opt,name=archived_at,json=archivedAt,proto3" json:"archived_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveDocumentResponse) Reset() {
	*x = ArchiveDocumentResponse{}
	mi := &file_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveDocumentResponse) ProtoMessage() {}

func (x *ArchiveDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveDocumentResponse.ProtoReflect.Descriptor instead.
func (*ArchiveDocumentResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{20}
}

func (x *ArchiveDocumentResponse) GetArchived() bool {
	if x != nil {
		return x.Archived
	}
	return false
}

func (x *ArchiveDocumentResponse) GetArchivedAt() string {
	if x != nil {
		return x.ArchivedAt
	}
	return ""
}

type StartWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorUserId   string                 `protobuf:"bytes,1,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWorkflowRequest) Reset() {
	*x = StartWorkflowRequest{}
	mi := &file_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkflowRequest) ProtoMessage() {}

func (x *StartWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkflowRequest.ProtoReflect.Descriptor instead.
func (*StartWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{21}
}

func (x *StartWorkflowRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *StartWorkflowRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type ApproveStepRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ActorUserId     string                 `protobuf:"bytes,1,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	DocumentId      string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	StepCode        string                 `protobuf:"bytes,3,opt,name=step_code,json=stepCode,proto3" json:"step_code,omitempty"`
	ExpectedVersion int64                  `protobuf:"varint,4,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ApproveStepRequest) Reset() {
	*x = ApproveStepRequest{}
	mi := &file_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveStepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveStepRequest) ProtoMessage() {}

func (x *ApproveStepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveStepRequest.ProtoReflect.Descriptor instead.
func (*ApproveStepRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{22}
}

func (x *ApproveStepRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *ApproveStepRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *ApproveStepRequest) GetStepCode() string {
	if x != nil {
		return x.StepCode
	}
	return ""
}

func (x *ApproveStepRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type RejectStepRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ActorUserId     string                 `protobuf:"bytes,1,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	DocumentId      string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Reason          string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	ExpectedVersion int64                  `protobuf:"varint,4,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RejectStepRequest) Reset() {
	*x = RejectStepRequest{}
	mi := &file_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectStepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectStepRequest) ProtoMessage() {}

func (x *RejectStepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectStepRequest.ProtoReflect.Descriptor instead.
func (*RejectStepRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{23}
}

func (x *RejectStepRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *RejectStepRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *RejectStepRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RejectStepRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type RequestChangesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ActorUserId     string                 `protobuf:"bytes,1,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	DocumentId      string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Comment         string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	ExpectedVersion int64                  `protobuf:"varint,4,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RequestChangesRequest) Reset() {
	*x = RequestChangesRequest{}
	mi := &file_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestChangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestChangesRequest) ProtoMessage() {}

func (x *RequestChangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestChangesRequest.ProtoReflect.Descriptor instead.
func (*RequestChangesRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{24}
}

func (x *RequestChangesRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *RequestChangesRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *RequestChangesRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *RequestChangesRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type SubmitWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorUserId   string                 `protobuf:"bytes,1,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitWorkflowRequest) Reset() {
	*x = SubmitWorkflowRequest{}
	mi := &file_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitWorkflowRequest) ProtoMessage() {}

func (x *SubmitWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitWorkflowRequest.ProtoReflect.Descriptor instead.
func (*SubmitWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{25}
}

func (x *SubmitWorkflowRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *SubmitWorkflowRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type ApproveWorkflowRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ActorUserId     string                 `protobuf:"bytes,1,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	DocumentId      string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	ExpectedVersion int64                  `protobuf:"varint,3,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ApproveWorkflowRequest) Reset() {
	*x = ApproveWorkflowRequest{}
	mi := &file_service_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApproveWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveWorkflowRequest) ProtoMessage() {}

func (x *ApproveWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveWorkflowRequest.ProtoReflect.Descriptor instead.
func (*ApproveWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{26}
}

func (x *ApproveWorkflowRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *ApproveWorkflowRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *ApproveWorkflowRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type RequestWorkflowChangesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ActorUserId     string                 `protobuf:"bytes,1,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	DocumentId      string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Comment         string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	ExpectedVersion int64                  `protobuf:"varint,4,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RequestWorkflowChangesRequest) Reset() {
	*x = RequestWorkflowChangesRequest{}
	mi := &file_service_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestWorkflowChangesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestWorkflowChangesRequest) ProtoMessage() {}

func (x *RequestWorkflowChangesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestWorkflowChangesRequest.ProtoReflect.Descriptor instead.
func (*RequestWorkflowChangesRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{27}
}

func (x *RequestWorkflowChangesRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *RequestWorkflowChangesRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *RequestWorkflowChangesRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

func (x *RequestWorkflowChangesRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type StartSignatureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorUserId   string                 `protobuf:"bytes,1,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Signers       []*SignatureSigner     `protobuf:"bytes,3,rep,name=signers,proto3" json:"signers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartSignatureRequest) Reset() {
	*x = StartSignatureRequest{}
	mi := &file_service_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartSignatureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartSignatureRequest) ProtoMessage() {}

func (x *StartSignatureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartSignatureRequest.ProtoReflect.Descriptor instead.
func (*StartSignatureRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{28}
}

func (x *StartSignatureRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *StartSignatureRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *StartSignatureRequest) GetSigners() []*SignatureSigner {
	if x != nil {
		return x.Signers
	}
	return nil
}

type SignatureSigner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DueAt         string                 `protobuf:"bytes,2,opt,name=due_at,json=dueAt,proto3" json:"due_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignatureSigner) Reset() {
	*x = SignatureSigner{}
	mi := &file_service_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignatureSigner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignatureSigner) ProtoMessage() {}

func (x *SignatureSigner) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignatureSigner.ProtoReflect.Descriptor instead.
func (*SignatureSigner) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{29}
}

func (x *SignatureSigner) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SignatureSigner) GetDueAt() string {
	if x != nil {
		return x.DueAt
	}
	return ""
}

type RecordSignatureCallbackRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ActorUserId        string                 `protobuf:"bytes,1,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	SignatureRequestId string                 `protobuf:"bytes,2,opt,name=signature_request_id,json=signatureRequestId,proto3" json:"signature_request_id,omitempty"`
	Status             string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	ProviderRef        string                 `protobuf:"bytes,4,opt,name=provider_ref,json=providerRef,proto3" json:"provider_ref,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RecordSignatureCallbackRequest) Reset() {
	*x = RecordSignatureCallbackRequest{}
	mi := &file_service_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordSignatureCallbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordSignatureCallbackRequest) ProtoMessage() {}

func (x *RecordSignatureCallbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordSignatureCallbackRequest.ProtoReflect.Descriptor instead.
func (*RecordSignatureCallbackRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{30}
}

func (x *RecordSignatureCallbackRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *RecordSignatureCallbackRequest) GetSignatureRequestId() string {
	if x != nil {
		return x.SignatureRequestId
	}
	return ""
}

func (x *RecordSignatureCallbackRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RecordSignatureCallbackRequest) GetProviderRef() string {
	if x != nil {
		return x.ProviderRef
	}
	return ""
}

type GetSignatureStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorUserId   string                 `protobuf:"bytes,1,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSignatureStatusRequest) Reset() {
	*x = GetSignatureStatusRequest{}
	mi := &file_service_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSignatureStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignatureStatusRequest) ProtoMessage() {}

func (x *GetSignatureStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignatureStatusRequest.ProtoReflect.Descriptor instead.
func (*GetSignatureStatusRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{31}
}

func (x *GetSignatureStatusRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *GetSignatureStatusRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type EmitNotificationRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ActorUserId     string                 `protobuf:"bytes,1,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	EventType       string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	RecipientUserId string                 `protobuf:"bytes,3,opt,name=recipient_user_id,json=recipientUserId,proto3" json:"recipient_user_id,omitempty"`
	DocumentId      string                 `protobuf:"bytes,4,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EmitNotificationRequest) Reset() {
	*x = EmitNotificationRequest{}
	mi := &file_service_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitNotificationRequest) ProtoMessage() {}

func (x *EmitNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitNotificationRequest.ProtoReflect.Descriptor instead.
func (*EmitNotificationRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{32}
}

func (x *EmitNotificationRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *EmitNotificationRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *EmitNotificationRequest) GetRecipientUserId() string {
	if x != nil {
		return x.RecipientUserId
	}
	return ""
}

func (x *EmitNotificationRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

type EmitNotificationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EmitNotificationResponse) Reset() {
	*x = EmitNotificationResponse{}
	mi := &file_service_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitNotificationResponse) ProtoMessage() {}

func (x *EmitNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitNotificationResponse.ProtoReflect.Descriptor instead.
func (*EmitNotificationResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{33}
}

func (x *EmitNotificationResponse) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

type RetryFailedNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorUserId   string                 `protobuf:"bytes,1,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	BatchSize     int32                  `protobuf:"varint,2,opt,name=batch_size,json=batchSize,proto3" json:"batch_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryFailedNotificationsRequest) Reset() {
	*x = RetryFailedNotificationsRequest{}
	mi := &file_service_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryFailedNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryFailedNotificationsRequest) ProtoMessage() {}

func (x *RetryFailedNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryFailedNotificationsRequest.ProtoReflect.Descriptor instead.
func (*RetryFailedNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{34}
}

func (x *RetryFailedNotificationsRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *RetryFailedNotificationsRequest) GetBatchSize() int32 {
	if x != nil {
		return x.BatchSize
	}
	return 0
}

type RetryFailedNotificationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RetriedCount  int32                  `protobuf:"varint,1,opt,name=retried_count,json=retriedCount,proto3" json:"retried_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryFailedNotificationsResponse) Reset() {
	*x = RetryFailedNotificationsResponse{}
	mi := &file_service_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryFailedNotificationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryFailedNotificationsResponse) ProtoMessage() {}

func (x *RetryFailedNotificationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryFailedNotificationsResponse.ProtoReflect.Descriptor instead.
func (*RetryFailedNotificationsResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{35}
}

func (x *RetryFailedNotificationsResponse) GetRetriedCount() int32 {
	if x != nil {
		return x.RetriedCount
	}
	return 0
}

type SyncSearchProjectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorUserId   string                 `protobuf:"bytes,1,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncSearchProjectionRequest) Reset() {
	*x = SyncSearchProjectionRequest{}
	mi := &file_service_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncSearchProjectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncSearchProjectionRequest) ProtoMessage() {}

func (x *SyncSearchProjectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncSearchProjectionRequest.ProtoReflect.Descriptor instead.
func (*SyncSearchProjectionRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{36}
}

func (x *SyncSearchProjectionRequest) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *SyncSearchProjectionRequest) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *SyncSearchProjectionRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type SyncSearchProjectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Synced        bool                   `protobuf:"varint,1,opt,name=synced,proto3" json:"synced,omitempty"`
	IndexedAt     string                 `protobuf:"bytes,2,opt,name=indexed_at,json=indexedAt,proto3" json:"indexed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncSearchProjectionResponse) Reset() {
	*x = SyncSearchProjectionResponse{}
	mi := &file_service_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncSearchProjectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncSearchProjectionResponse) ProtoMessage() {}

func (x *SyncSearchProjectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncSearchProjectionResponse.ProtoReflect.Descriptor instead.
func (*SyncSearchProjectionResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{37}
}

func (x *SyncSearchProjectionResponse) GetSynced() bool {
	if x != nil {
		return x.Synced
	}
	return false
}

func (x *SyncSearchProjectionResponse) GetIndexedAt() string {
	if x != nil {
		return x.IndexedAt
	}
	return ""
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\n" +
	"service.v1\"'\n" +
	"\vPingRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xf5\x01\n" +
	"\bDocument\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\"\n" +
	"\rowner_user_id\x18\x05 \x01(\tR\vownerUserId\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x03R\aversion\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x122\n" +
	"\x15content_document_json\x18\b \x01(\tR\x13contentDocumentJson\"\xab\x02\n" +
	"\x14EditorControlProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fcontext_type\x18\x02 \x01(\tR\vcontextType\x12\x1f\n" +
	"\vcontext_key\x18\x03 \x01(\tR\n" +
	"contextKey\x12)\n" +
	"\x10enabled_controls\x18\x04 \x03(\tR\x0fenabledControls\x12+\n" +
	"\x11disabled_controls\x18\x05 \x03(\tR\x10disabledControls\x12\x1b\n" +
	"\tis_active\x18\x06 \x01(\bR\bisActive\x12+\n" +
	"\x12updated_by_user_id\x18\a \x01(\tR\x0fupdatedByUserId\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\tupdatedAt\"\x98\x01\n" +
	"\x0eExportArtifact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"\xd1\x02\n" +
	"\rExportRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12%\n" +
	"\x0esource_version\x18\x04 \x01(\x03R\rsourceVersion\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"error_code\x18\x06 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\x126\n" +
	"\bartifact\x18\b \x01(\v2\x1a.service.v1.ExportArtifactR\bartifact\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\"\xd0\x01\n" +
	"\x10WorkflowInstance\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12*\n" +
	"\x11current_step_code\x18\x03 \x01(\tR\x0fcurrentStepCode\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12(\n" +
	"\x10assigned_user_id\x18\x05 \x01(\tR\x0eassignedUserId\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\tR\tupdatedAt\"\x95\x01\n" +
	"\x10SignatureRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\fprovider_ref\x18\x04 \x01(\tR\vproviderRef\x12\x15\n" +
	"\x06due_at\x18\x05 \x01(\tR\x05dueAt\"\x9e\x01\n" +
	"\x12CreateDraftRequest\x12\"\n" +
	"\ractor_user_id\x18\x01 \x01(\tR\vactorUserId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x122\n" +
	"\x15content_document_json\x18\x04 \x01(\tR\x13contentDocumentJson\"\xe6\x01\n" +
	"\x12UpdateDraftRequest\x12\"\n" +
	"\ractor_user_id\x18\x01 \x01(\tR\vactorUserId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12)\n" +
	"\x10expected_version\x18\x04 \x01(\x03R\x0fexpectedVersion\x122\n" +
	"\x15content_document_json\x18\x05 \x01(\tR\x13contentDocumentJson\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\"Y\n" +
	"\x12GetDocumentRequest\x12\"\n" +
	"\ractor_user_id\x18\x01 \x01(\tR\vactorUserId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\"\x88\x01\n" +
	"\x1eGetEditorControlProfileRequest\x12\"\n" +
	"\ractor_user_id\x18\x01 \x01(\tR\vactorUserId\x12!\n" +
	"\fcontext_type\x18\x02 \x01(\tR\vcontextType\x12\x1f\n" +
	"\vcontext_key\x18\x03 \x01(\tR\n" +
	"contextKey\"\xdb\x01\n" +
	"!UpdateEditorControlProfileRequest\x12\"\n" +
	"\ractor_user_id\x18\x01 \x01(\tR\vactorUserId\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x02 \x01(\tR\tprofileId\x12)\n" +
	"\x10enabled_controls\x18\x03 \x03(\tR\x0fenabledControls\x12+\n" +
	"\x11disabled_controls\x18\x04 \x03(\tR\x10disabledControls\x12\x1b\n" +
	"\tis_active\x18\x05 \x01(\bR\bisActive\"\x99\x01\n" +
	"\x13CreateExportPayload\x12\"\n" +
	"\ractor_user_id\x18\x01 \x01(\tR\vactorUserId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12%\n" +
	"\x0esource_version\x18\x04 \x01(\x03R\rsourceVersion\"\x8a\x01\n" +
	"\x17GetExportRequestRequest\x12\"\n" +
	"\ractor_user_id\x18\x01 \x01(\tR\vactorUserId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12*\n" +
	"\x11export_request_id\x18\x03 \x01(\tR\x0fexportRequestId\"\x90\x01\n" +
	"\x1dDownloadExportArtifactRequest\x12\"\n" +
	"\ractor_user_id\x18\x01 \x01(\tR\vactorUserId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12*\n" +
	"\x11export_request_id\x18\x03 \x01(\tR\x0fexportRequestId\"n\n" +
	"\x1eDownloadExportArtifactResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1b\n" +
	"\tfile_name\x18\x02 \x01(\tR\bfileName\x12\x1b\n" +
	"\tmime_type\x18\x03 \x01(\tR\bmimeType\"\xb4\x01\n" +
	"\x16SearchDocumentsRequest\x12\"\n" +
	"\ractor_user_id\x18\x01 \x01(\tR\vactorUserId\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x06 \x01(\x05R\x06offset\"[\n" +
	"\x17SearchDocumentsResponse\x12*\n" +
	"\x05items\x18\x01 \x03(\v2\x14.service.v1.DocumentR\x05items\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x88\x01\n" +
	"\x16ArchiveDocumentRequest\x12\"\n" +
	"\ractor_user_id\x18\x01 \x01(\tR\vactorUserId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12)\n" +
	"\x10expected_version\x18\x03 \x01(\x03R\x0fexpectedVersion\"V\n" +
	"\x17ArchiveDocumentResponse\x12\x1a\n" +
	"\barchived\x18\x01 \x01(\bR\barchived\x12\x1f\n" +
	"\varchived_at\x18\x02 \x01(\tR\n" +
	"archivedAt\"[\n" +
	"\x14StartWorkflowRequest\x12\"\n" +
	"\ractor_user_id\x18\x01 \x01(\tR\vactorUserId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\"\xa1\x01\n" +
	"\x12ApproveStepRequest\x12\"\n" +
	"\ractor_user_id\x18\x01 \x01(\tR\vactorUserId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x1b\n" +
	"\tstep_code\x18\x03 \x01(\tR\bstepCode\x12)\n" +
	"\x10expected_version\x18\x04 \x01(\x03R\x0fexpectedVersion\"\x9b\x01\n" +
	"\x11RejectStepRequest\x12\"\n" +
	"\ractor_user_id\x18\x01 \x01(\tR\vactorUserId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12)\n" +
	"\x10expected_version\x18\x04 \x01(\x03R\x0fexpectedVersion\"\xa1\x01\n" +
	"\x15RequestChangesRequest\x12\"\n" +
	"\ractor_user_id\x18\x01 \x01(\tR\vactorUserId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\x12)\n" +
	"\x10expected_version\x18\x04 \x01(\x03R\x0fexpectedVersion\"\\\n" +
	"\x15SubmitWorkflowRequest\x12\"\n" +
	"\ractor_user_id\x18\x01 \x01(\tR\vactorUserId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\"\x88\x01\n" +
	"\x16ApproveWorkflowRequest\x12\"\n" +
	"\ractor_user_id\x18\x01 \x01(\tR\vactorUserId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12)\n" +
	"\x10expected_version\x18\x03 \x01(\x03R\x0fexpectedVersion\"\xa9\x01\n" +
	"\x1dRequestWorkflowChangesRequest\x12\"\n" +
	"\ractor_user_id\x18\x01 \x01(\tR\vactorUserId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\x12)\n" +
	"\x10expected_version\x18\x04 \x01(\x03R\x0fexpectedVersion\"\x93\x01\n" +
	"\x15StartSignatureRequest\x12\"\n" +
	"\ractor_user_id\x18\x01 \x01(\tR\vactorUserId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x125\n" +
	"\asigners\x18\x03 \x03(\v2\x1b.service.v1.SignatureSignerR\asigners\"A\n" +
	"\x0fSignatureSigner\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x15\n" +
	"\x06due_at\x18\x02 \x01(\tR\x05dueAt\"\xb1\x01\n" +
	"\x1eRecordSignatureCallbackRequest\x12\"\n" +
	"\ractor_user_id\x18\x01 \x01(\tR\vactorUserId\x120\n" +
	"\x14signature_request_id\x18\x02 \x01(\tR\x12signatureRequestId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12!\n" +
	"\fprovider_ref\x18\x04 \x01(\tR\vproviderRef\"`\n" +
	"\x19GetSignatureStatusRequest\x12\"\n" +
	"\ractor_user_id\x18\x01 \x01(\tR\vactorUserId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\"\xa9\x01\n" +
	"\x17EmitNotificationRequest\x12\"\n" +
	"\ractor_user_id\x18\x01 \x01(\tR\vactorUserId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12*\n" +
	"\x11recipient_user_id\x18\x03 \x01(\tR\x0frecipientUserId\x12\x1f\n" +
	"\vdocument_id\x18\x04 \x01(\tR\n" +
	"documentId\"C\n" +
	"\x18EmitNotificationResponse\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\"d\n" +
	"\x1fRetryFailedNotificationsRequest\x12\"\n" +
	"\ractor_user_id\x18\x01 \x01(\tR\vactorUserId\x12\x1d\n" +
	"\n" +
	"batch_size\x18\x02 \x01(\x05R\tbatchSize\"G\n" +
	" RetryFailedNotificationsResponse\x12#\n" +
	"\rretried_count\x18\x01 \x01(\x05R\fretriedCount\"|\n" +
	"\x1bSyncSearchProjectionRequest\x12\"\n" +
	"\ractor_user_id\x18\x01 \x01(\tR\vactorUserId\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"U\n" +
	"\x1cSyncSearchProjectionResponse\x12\x16\n" +
	"\x06synced\x18\x01 \x01(\bR\x06synced\x12\x1d\n" +
	"\n" +
	"indexed_at\x18\x02 \x01(\tR\tindexedAt2K\n" +
	"\x0eExampleService\x129\n" +
	"\x04Ping\x12\x17.service.v1.PingRequest\x1a\x18.service.v1.PingResponse2\x9b\t\n" +
	"\x17DocumentWorkflowService\x12C\n" +
	"\vCreateDraft\x12\x1e.service.v1.CreateDraftRequest\x1a\x14.service.v1.Document\x12C\n" +
	"\vUpdateDraft\x12\x1e.service.v1.UpdateDraftRequest\x1a\x14.service.v1.Document\x12C\n" +
	"\vGetDocument\x12\x1e.service.v1.GetDocumentRequest\x1a\x14.service.v1.Document\x12g\n" +
	"\x17GetEditorControlProfile\x12*.service.v1.GetEditorControlProfileRequest\x1a .service.v1.EditorControlProfile\x12m\n" +
	"\x1aUpdateEditorControlProfile\x12-.service.v1.UpdateEditorControlProfileRequest\x1a .service.v1.EditorControlProfile\x12Q\n" +
	"\x13CreateExportRequest\x12\x1f.service.v1.CreateExportPayload\x1a\x19.service.v1.ExportRequest\x12R\n" +
	"\x10GetExportRequest\x12#.service.v1.GetExportRequestRequest\x1a\x19.service.v1.ExportRequest\x12o\n" +
	"\x16DownloadExportArtifact\x12).service.v1.DownloadExportArtifactRequest\x1a*.service.v1.DownloadExportArtifactResponse\x12Z\n" +
	"\x0fSearchDocuments\x12\".service.v1.SearchDocumentsRequest\x1a#.service.v1.SearchDocumentsResponse\x12Q\n" +
	"\x0eSubmitWorkflow\x12!.service.v1.SubmitWorkflowRequest\x1a\x1c.service.v1.WorkflowInstance\x12S\n" +
	"\x0fApproveWorkflow\x12\".service.v1.ApproveWorkflowRequest\x1a\x1c.service.v1.WorkflowInstance\x12a\n" +
	"\x16RequestWorkflowChanges\x12).service.v1.RequestWorkflowChangesRequest\x1a\x1c.service.v1.WorkflowInstance\x12Z\n" +
	"\x0fArchiveDocument\x12\".service.v1.ArchiveDocumentRequest\x1a#.service.v1.ArchiveDocumentResponse2\xb8\x03\n" +
	"\x19SearchNotificationService\x12i\n" +
	"\x14SyncSearchProjection\x12'.service.v1.SyncSearchProjectionRequest\x1a(.service.v1.SyncSearchProjectionResponse\x12Z\n" +
	"\x0fSearchDocuments\x12\".service.v1.SearchDocumentsRequest\x1a#.service.v1.SearchDocumentsResponse\x12]\n" +
	"\x10EmitNotification\x12#.service.v1.EmitNotificationRequest\x1a$.service.v1.EmitNotificationResponse\x12u\n" +
	"\x18RetryFailedNotifications\x12+.service.v1.RetryFailedNotificationsRequest\x1a,.service.v1.RetryFailedNotificationsResponse2\x88\a\n" +
	"\x0fDocumentService\x12C\n" +
	"\vCreateDraft\x12\x1e.service.v1.CreateDraftRequest\x1a\x14.service.v1.Document\x12C\n" +
	"\vUpdateDraft\x12\x1e.service.v1.UpdateDraftRequest\x1a\x14.service.v1.Document\x12C\n" +
	"\vGetDocument\x12\x1e.service.v1.GetDocumentRequest\x1a\x14.service.v1.Document\x12g\n" +
	"\x17GetEditorControlProfile\x12*.service.v1.GetEditorControlProfileRequest\x1a .service.v1.EditorControlProfile\x12m\n" +
	"\x1aUpdateEditorControlProfile\x12-.service.v1.UpdateEditorControlProfileRequest\x1a .service.v1.EditorControlProfile\x12Q\n" +
	"\x13CreateExportRequest\x12\x1f.service.v1.CreateExportPayload\x1a\x19.service.v1.ExportRequest\x12R\n" +
	"\x10GetExportRequest\x12#.service.v1.GetExportRequestRequest\x1a\x19.service.v1.ExportRequest\x12o\n" +
	"\x16DownloadExportArtifact\x12).service.v1.DownloadExportArtifactRequest\x1a*.service.v1.DownloadExportArtifactResponse\x12Z\n" +
	"\x0fSearchDocuments\x12\".service.v1.SearchDocumentsRequest\x1a#.service.v1.SearchDocumentsResponse\x12Z\n" +
	"\x0fArchiveDocument\x12\".service.v1.ArchiveDocumentRequest\x1a#.service.v1.ArchiveDocumentResponse2\xcd\x02\n" +
	"\x0fWorkflowService\x12O\n" +
	"\rStartWorkflow\x12 .service.v1.StartWorkflowRequest\x1a\x1c.service.v1.WorkflowInstance\x12K\n" +
	"\vApproveStep\x12\x1e.service.v1.ApproveStepRequest\x1a\x1c.service.v1.WorkflowInstance\x12I\n" +
	"\n" +
	"RejectStep\x12\x1d.service.v1.RejectStepRequest\x1a\x1c.service.v1.WorkflowInstance\x12Q\n" +
	"\x0eRequestChanges\x12!.service.v1.RequestChangesRequest\x1a\x1c.service.v1.WorkflowInstance2\xa5\x02\n" +
	"\x10SignatureService\x12Q\n" +
	"\x0eStartSignature\x12!.service.v1.StartSignatureRequest\x1a\x1c.service.v1.SignatureRequest\x12c\n" +
	"\x17RecordSignatureCallback\x12*.service.v1.RecordSignatureCallbackRequest\x1a\x1c.service.v1.SignatureRequest\x12Y\n" +
	"\x12GetSignatureStatus\x12%.service.v1.GetSignatureStatusRequest\x1a\x1c.service.v1.SignatureRequest2\xeb\x01\n" +
	"\x13NotificationService\x12]\n" +
	"\x10EmitNotification\x12#.service.v1.EmitNotificationRequest\x1a$.service.v1.EmitNotificationResponse\x12u\n" +
	"\x18RetryFailedNotifications\x12+.service.v1.RetryFailedNotificationsRequest\x1a,.service.v1.RetryFailedNotificationsResponseB\x18Z\x16edo/shared/proto/pb;pbb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_service_proto_goTypes = []any{
	(*PingRequest)(nil),                       // 0: service.v1.PingRequest
	(*PingResponse)(nil),                      // 1: service.v1.PingResponse
	(*Document)(nil),                          // 2: service.v1.Document
	(*EditorControlProfile)(nil),              // 3: service.v1.EditorControlProfile
	(*ExportArtifact)(nil),                    // 4: service.v1.ExportArtifact
	(*ExportRequest)(nil),                     // 5: service.v1.ExportRequest
	(*WorkflowInstance)(nil),                  // 6: service.v1.WorkflowInstance
	(*SignatureRequest)(nil),                  // 7: service.v1.SignatureRequest
	(*CreateDraftRequest)(nil),                // 8: service.v1.CreateDraftRequest
	(*UpdateDraftRequest)(nil),                // 9: service.v1.UpdateDraftRequest
	(*GetDocumentRequest)(nil),                // 10: service.v1.GetDocumentRequest
	(*GetEditorControlProfileRequest)(nil),    // 11: service.v1.GetEditorControlProfileRequest
	(*UpdateEditorControlProfileRequest)(nil), // 12: service.v1.UpdateEditorControlProfileRequest
	(*CreateExportPayload)(nil),               // 13: service.v1.CreateExportPayload
	(*GetExportRequestRequest)(nil),           // 14: service.v1.GetExportRequestRequest
	(*DownloadExportArtifactRequest)(nil),     // 15: service.v1.DownloadExportArtifactRequest
	(*DownloadExportArtifactResponse)(nil),    // 16: service.v1.DownloadExportArtifactResponse
	(*SearchDocumentsRequest)(nil),            // 17: service.v1.SearchDocumentsRequest
	(*SearchDocumentsResponse)(nil),           // 18: service.v1.SearchDocumentsResponse
	(*ArchiveDocumentRequest)(nil),            // 19: service.v1.ArchiveDocumentRequest
	(*ArchiveDocumentResponse)(nil),           // 20: service.v1.ArchiveDocumentResponse
	(*StartWorkflowRequest)(nil),              // 21: service.v1.StartWorkflowRequest
	(*ApproveStepRequest)(nil),                // 22: service.v1.ApproveStepRequest
	(*RejectStepRequest)(nil),                 // 23: service.v1.RejectStepRequest
	(*RequestChangesRequest)(nil),             // 24: service.v1.RequestChangesRequest
	(*SubmitWorkflowRequest)(nil),             // 25: service.v1.SubmitWorkflowRequest
	(*ApproveWorkflowRequest)(nil),            // 26: service.v1.ApproveWorkflowRequest
	(*RequestWorkflowChangesRequest)(nil),     // 27: service.v1.RequestWorkflowChangesRequest
	(*StartSignatureRequest)(nil),             // 28: service.v1.StartSignatureRequest
	(*SignatureSigner)(nil),                   // 29: service.v1.SignatureSigner
	(*RecordSignatureCallbackRequest)(nil),    // 30: service.v1.RecordSignatureCallbackRequest
	(*GetSignatureStatusRequest)(nil),         // 31: service.v1.GetSignatureStatusRequest
	(*EmitNotificationRequest)(nil),           // 32: service.v1.EmitNotificationRequest
	(*EmitNotificationResponse)(nil),          // 33: service.v1.EmitNotificationResponse
	(*RetryFailedNotificationsRequest)(nil),   // 34: service.v1.RetryFailedNotificationsRequest
	(*RetryFailedNotificationsResponse)(nil),  // 35: service.v1.RetryFailedNotificationsResponse
	(*SyncSearchProjectionRequest)(nil),       // 36: service.v1.SyncSearchProjectionRequest
	(*SyncSearchProjectionResponse)(nil),      // 37: service.v1.SyncSearchProjectionResponse
}
var file_service_proto_depIdxs = []int32{
	4,  // 0: service.v1.ExportRequest.artifact:type_name -> service.v1.ExportArtifact
	2,  // 1: service.v1.SearchDocumentsResponse.items:type_name -> service.v1.Document
	29, // 2: service.v1.StartSignatureRequest.signers:type_name -> service.v1.SignatureSigner
	0,  // 3: service.v1.ExampleService.Ping:input_type -> service.v1.PingRequest
	8,  // 4: service.v1.DocumentWorkflowService.CreateDraft:input_type -> service.v1.CreateDraftRequest
	9,  // 5: service.v1.DocumentWorkflowService.UpdateDraft:input_type -> service.v1.UpdateDraftRequest
	10, // 6: service.v1.DocumentWorkflowService.GetDocument:input_type -> service.v1.GetDocumentRequest
	11, // 7: service.v1.DocumentWorkflowService.GetEditorControlProfile:input_type -> service.v1.GetEditorControlProfileRequest
	12, // 8: service.v1.DocumentWorkflowService.UpdateEditorControlProfile:input_type -> service.v1.UpdateEditorControlProfileRequest
	13, // 9: service.v1.DocumentWorkflowService.CreateExportRequest:input_type -> service.v1.CreateExportPayload
	14, // 10: service.v1.DocumentWorkflowService.GetExportRequest:input_type -> service.v1.GetExportRequestRequest
	15, // 11: service.v1.DocumentWorkflowService.DownloadExportArtifact:input_type -> service.v1.DownloadExportArtifactRequest
	17, // 12: service.v1.DocumentWorkflowService.SearchDocuments:input_type -> service.v1.SearchDocumentsRequest
	25, // 13: service.v1.DocumentWorkflowService.SubmitWorkflow:input_type -> service.v1.SubmitWorkflowRequest
	26, // 14: service.v1.DocumentWorkflowService.ApproveWorkflow:input_type -> service.v1.ApproveWorkflowRequest
	27, // 15: service.v1.DocumentWorkflowService.RequestWorkflowChanges:input_type -> service.v1.RequestWorkflowChangesRequest
	19, // 16: service.v1.DocumentWorkflowService.ArchiveDocument:input_type -> service.v1.ArchiveDocumentRequest
	36, // 17: service.v1.SearchNotificationService.SyncSearchProjection:input_type -> service.v1.SyncSearchProjectionRequest
	17, // 18: service.v1.SearchNotificationService.SearchDocuments:input_type -> service.v1.SearchDocumentsRequest
	32, // 19: service.v1.SearchNotificationService.EmitNotification:input_type -> service.v1.EmitNotificationRequest
	34, // 20: service.v1.SearchNotificationService.RetryFailedNotifications:input_type -> service.v1.RetryFailedNotificationsRequest
	8,  // 21: service.v1.DocumentService.CreateDraft:input_type -> service.v1.CreateDraftRequest
	9,  // 22: service.v1.DocumentService.UpdateDraft:input_type -> service.v1.UpdateDraftRequest
	10, // 23: service.v1.DocumentService.GetDocument:input_type -> service.v1.GetDocumentRequest
	11, // 24: service.v1.DocumentService.GetEditorControlProfile:input_type -> service.v1.GetEditorControlProfileRequest
	12, // 25: service.v1.DocumentService.UpdateEditorControlProfile:input_type -> service.v1.UpdateEditorControlProfileRequest
	13, // 26: service.v1.DocumentService.CreateExportRequest:input_type -> service.v1.CreateExportPayload
	14, // 27: service.v1.DocumentService.GetExportRequest:input_type -> service.v1.GetExportRequestRequest
	15, // 28: service.v1.DocumentService.DownloadExportArtifact:input_type -> service.v1.DownloadExportArtifactRequest
	17, // 29: service.v1.DocumentService.SearchDocuments:input_type -> service.v1.SearchDocumentsRequest
	19, // 30: service.v1.DocumentService.ArchiveDocument:input_type -> service.v1.ArchiveDocumentRequest
	21, // 31: service.v1.WorkflowService.StartWorkflow:input_type -> service.v1.StartWorkflowRequest
	22, // 32: service.v1.WorkflowService.ApproveStep:input_type -> service.v1.ApproveStepRequest
	23, // 33: service.v1.WorkflowService.RejectStep:input_type -> service.v1.RejectStepRequest
	24, // 34: service.v1.WorkflowService.RequestChanges:input_type -> service.v1.RequestChangesRequest
	28, // 35: service.v1.SignatureService.StartSignature:input_type -> service.v1.StartSignatureRequest
	30, // 36: service.v1.SignatureService.RecordSignatureCallback:input_type -> service.v1.RecordSignatureCallbackRequest
	31, // 37: service.v1.SignatureService.GetSignatureStatus:input_type -> service.v1.GetSignatureStatusRequest
	32, // 38: service.v1.NotificationService.EmitNotification:input_type -> service.v1.EmitNotificationRequest
	34, // 39: service.v1.NotificationService.RetryFailedNotifications:input_type -> service.v1.RetryFailedNotificationsRequest
	1,  // 40: service.v1.ExampleService.Ping:output_type -> service.v1.PingResponse
	2,  // 41: service.v1.DocumentWorkflowService.CreateDraft:output_type -> service.v1.Document
	2,  // 42: service.v1.DocumentWorkflowService.UpdateDraft:output_type -> service.v1.Document
	2,  // 43: service.v1.DocumentWorkflowService.GetDocument:output_type -> service.v1.Document
	3,  // 44: service.v1.DocumentWorkflowService.GetEditorControlProfile:output_type -> service.v1.EditorControlProfile
	3,  // 45: service.v1.DocumentWorkflowService.UpdateEditorControlProfile:output_type -> service.v1.EditorControlProfile
	5,  // 46: service.v1.DocumentWorkflowService.CreateExportRequest:output_type -> service.v1.ExportRequest
	5,  // 47: service.v1.DocumentWorkflowService.GetExportRequest:output_type -> service.v1.ExportRequest
	16, // 48: service.v1.DocumentWorkflowService.DownloadExportArtifact:output_type -> service.v1.DownloadExportArtifactResponse
	18, // 49: service.v1.DocumentWorkflowService.SearchDocuments:output_type -> service.v1.SearchDocumentsResponse
	6,  // 50: service.v1.DocumentWorkflowService.SubmitWorkflow:output_type -> service.v1.WorkflowInstance
	6,  // 51: service.v1.DocumentWorkflowService.ApproveWorkflow:output_type -> service.v1.WorkflowInstance
	6,  // 52: service.v1.DocumentWorkflowService.RequestWorkflowChanges:output_type -> service.v1.WorkflowInstance
	20, // 53: service.v1.DocumentWorkflowService.ArchiveDocument:output_type -> service.v1.ArchiveDocumentResponse
	37, // 54: service.v1.SearchNotificationService.SyncSearchProjection:output_type -> service.v1.SyncSearchProjectionResponse
	18, // 55: service.v1.SearchNotificationService.SearchDocuments:output_type -> service.v1.SearchDocumentsResponse
	33, // 56: service.v1.SearchNotificationService.EmitNotification:output_type -> service.v1.EmitNotificationResponse
	35, // 57: service.v1.SearchNotificationService.RetryFailedNotifications:output_type -> service.v1.RetryFailedNotificationsResponse
	2,  // 58: service.v1.DocumentService.CreateDraft:output_type -> service.v1.Document
	2,  // 59: service.v1.DocumentService.UpdateDraft:output_type -> service.v1.Document
	2,  // 60: service.v1.DocumentService.GetDocument:output_type -> service.v1.Document
	3,  // 61: service.v1.DocumentService.GetEditorControlProfile:output_type -> service.v1.EditorControlProfile
	3,  // 62: service.v1.DocumentService.UpdateEditorControlProfile:output_type -> service.v1.EditorControlProfile
	5,  // 63: service.v1.DocumentService.CreateExportRequest:output_type -> service.v1.ExportRequest
	5,  // 64: service.v1.DocumentService.GetExportRequest:output_type -> service.v1.ExportRequest
	16, // 65: service.v1.DocumentService.DownloadExportArtifact:output_type -> service.v1.DownloadExportArtifactResponse
	18, // 66: service.v1.DocumentService.SearchDocuments:output_type -> service.v1.SearchDocumentsResponse
	20, // 67: service.v1.DocumentService.ArchiveDocument:output_type -> service.v1.ArchiveDocumentResponse
	6,  // 68: service.v1.WorkflowService.StartWorkflow:output_type -> service.v1.WorkflowInstance
	6,  // 69: service.v1.WorkflowService.ApproveStep:output_type -> service.v1.WorkflowInstance
	6,  // 70: service.v1.WorkflowService.RejectStep:output_type -> service.v1.WorkflowInstance
	6,  // 71: service.v1.WorkflowService.RequestChanges:output_type -> service.v1.WorkflowInstance
	7,  // 72: service.v1.SignatureService.StartSignature:output_type -> service.v1.SignatureRequest
	7,  // 73: service.v1.SignatureService.RecordSignatureCallback:output_type -> service.v1.SignatureRequest
	7,  // 74: service.v1.SignatureService.GetSignatureStatus:output_type -> service.v1.SignatureRequest
	33, // 75: service.v1.NotificationService.EmitNotification:output_type -> service.v1.EmitNotificationResponse
	35, // 76: service.v1.NotificationService.RetryFailedNotifications:output_type -> service.v1.RetryFailedNotificationsResponse
	40, // [40:77] is the sub-list for method output_type
	3,  // [3:40] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   7,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
